
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "2c82e18c6a32ce8c12eb246767e17139c5c3dfe9",
 "version": "1.1.171"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
