
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "356d96f338d818ea8a2704fec7c66b6c21abb276",
 "version": "0.6.post4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
