plugins:
  opc:
    # mandatory properties for every plugin
    module:
      package: metzoo-test-plugin
      import: from metzoo.plugins import empty

    # specific properties for the plugin (this could be anything)
    gateway: 10.224.24.119
    host_name: localhost
    server_name: Intellution.IntellutionGatewayOPCServer

  xls:
    # mandatory properties for every plugin
    module:
      package: tes-a
      import: from tes import a

    # specific properties for the plugin (this could be anything)
    path: /a/b/c
    filename: file*.xls
