__version__ = "0.2.11"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(HEAD detached at v0.2.11)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'ffb857c14b698a59dcab5b1bce14a1a77414e8d3'
__git_head_subject__ = 'Finished Release v0.2.11'
__git_head_message__ = ''
__git_dirty_diff__ = ''