
- instance:
    input:
        name: genetalk_db_machine 
        image_id: ami-fce3c696 
        subnet_id:
            from: subnet_id
        number: 1
        instance_type: t2.medium 
        security_group_ids:
            from: [security_group_id]
        tags:
            - tag:
                key: Name
                value: genetalk_test_instance 
    vpc:
       from_config: ./libaws/demo/vpc_config.yaml
    
    keypair:
        key: genetalk_access_key   
        delete_exists: True

    volumes:
        - volume:
            size: 20
            name: /dev/sda1

