language: python
sudo: false
cache:
  pip: true
  directories:
    - eggs
python: "2.7"
firefox: "latest"
install:
  - python bootstrap.py
  - bin/buildout -t 30
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "export ROBOT_HTTP_PORT=55001"
script: bin/test
