
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "62808805d28f27d7604f8669e9cedcee3c864131",
 "version": "2.10.93"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
