# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='districts_map',
            field=models.ImageField(blank=True, null=True, upload_to='notitications/maps/', verbose_name='Districts Map'),
        ),
    ]
