sudo: false
language: python

cache: pip

branches:
  except:
    - gh-pages

python:
  - "3.5"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - conda install --yes pytest
  # - pip install codecov
  # - pip install pytest-cov
  - pip install coveralls
  - pip install versioneer
  - pip install https://github.com/wtolson/pysis/archive/0.6.0.zip
  - pip install pytest-ipynb
  - pip install --pre .

# command to run tests, e.g. python setup.py test
script:
    # - py.test -s --cov .
    - cd pyciss/tests
    - py.test -v

after_success:
    - coveralls
    # - codecov

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aa8b92be81f54415501c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
