sudo: false
language: python
python: '3.4'
env:
- TOXENV=py34
- TOXENV=py27
- TOXENV=pep8
- TOXENV=cover
- TOXENV=docs
install:
- pip install tox
script:
- git clean -f -d -x
- tox
matrix:
  fast_finish: true
deploy:
  provider: pypi
  user: tripleodash-deploy
  distributions: sdist bdist_wheel
  password:
    secure: rD8HXdeQOzYbogZhAnWYdLuuuhezLHOO/yv5SY2S1qUbJEQbxTQO/Ib4vZaZO1gYSLB1+uNrmxR9mgZ2chsvXvss4R94ILspYoHKn7EgjUaGsx8G13xsvgEoFfYn13XR9faBYeFB4UrTOg86qZolhLtZW/wIpKOCsEO/eST+ML48z47uKf9tmdmYPbiqEr4Q8qGVw5yC7Add8/WQvv+EaXeoG1kBivpHffd7O7tLtXEJW/LBObZXGk5SoVcu447m0aawP+x8Lla6EtUhFtPeZOva+YTUrsUV0PBhpgVSIuVUb3hwHotNtz76URisHV78wUmReJ4gZwy+AbkiiJHROVvWxO1wZRU0ly3ph155AdSnRusv8fdxp7+eb6NCe91iEtEIjtva1ipT7LSr3S3V8evWwJWFHm3LdDxgNzuW2uA7LalVXvjy/CO1lnRw2aD0s3pM5hrJt/hR8zm4/Km2piWih+AIR+nQFimhbYkocLxIxUu6N/hFk5PEXeitQefpiNeVm6dnjiLVXAM8xJ5pDEHJoYOuO8GVlH8zmE4EDJaVu9ID6GaZbv7ipCA/RXqJ6BTD5emvNI0mELaNFOYfjhLnuSFsSjLqSC/KCj+a4WZfGZv53/JFMFLZW0TBiMbb5/pcHole9hn8G6KLjNpUy6hxSz7FJ53Vxdk/oMqAMzA=
  on:
    repo: d0ugal/python-tripleodash
    condition: "$TOXENV = py34"
    tags: true
