# Generated by setup.py for PyCBC on 2016-05-03 20:05:30 +0000.

version = '1.3.6'
date = '2016-02-03 18:29:42 +0000'
release = True

git_hash = 'db0979e63cd44ac6587a68650eb4d4eb7a8e5c6a'
git_branch = 'None'
git_tag = 'v1.3.6'
git_author = 'Larne Pekowsky <larne.pekowsky@ligo.org>'
git_committer = 'Larne Pekowsky <larne.pekowsky@ligo.org>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Unknown User <alex.nitz@ligo.org>'
git_build_date = '2016-05-03 20:05:30 +0000'
git_verbose_msg = """Branch: None
Tag: v1.3.6
Id: db0979e63cd44ac6587a68650eb4d4eb7a8e5c6a
Builder: Unknown User <alex.nitz@ligo.org>
Build date: 2016-05-03 20:05:30 +0000
Repository status is CLEAN: All modifications committed"""