# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shark', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editabletext',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='editabletext',
            name='line_nr',
        ),
    ]
