use_opc_time: True
time_format:  "%m/%d/%y %H:%M:%S"

metzoo:
  customer_key: c58d6977-999b-4c91-a7d0-d6e5a615d38b
  url:          http://staging-metzoo01.dev.edrans.net:8081

opc:
  #gateway:      localhost
  host_name:    localhost
  server_name:  Matrikon.OPC.Simulation.1

  mapping:
    Random.0: {agent: "opc.random.0", metric: "random.0"}
    Random.1: {agent: "opc.random.1", metric: "random.1"}
    Random.2: {agent: "opc.random.2", metric: "random.2"}
    Random.3: {agent: "opc.random.3", metric: "random.3"}
    Random.4: {agent: "opc.random.4", metric: "random.4"}
    Random.5: {agent: "opc.random.5", metric: "random.5"}
