
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d897729070a07d268feb42c8756bd09b59d14734",
 "version": "0.3.post9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
