
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.5.2.1'
version_full = '723ef7b3a8ee9b0375b495affd9f82d32c62ea09'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

