# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/colin/dev/HackEdit/hackedit-cobol/data/forms/dlg_configure_project.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(884, 752)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.combo_compilers = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_compilers.sizePolicy().hasHeightForWidth())
        self.combo_compilers.setSizePolicy(sizePolicy)
        self.combo_compilers.setObjectName("combo_compilers")
        self.horizontalLayout.addWidget(self.combo_compilers)
        self.bt_secondary_compilers = QtWidgets.QPushButton(Dialog)
        self.bt_secondary_compilers.setObjectName("bt_secondary_compilers")
        self.horizontalLayout.addWidget(self.bt_secondary_compilers)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.group_files = QtWidgets.QGroupBox(Dialog)
        self.group_files.setObjectName("group_files")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.group_files)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bt_add_build = QtWidgets.QToolButton(self.group_files)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.bt_add_build.setIcon(icon)
        self.bt_add_build.setObjectName("bt_add_build")
        self.horizontalLayout_2.addWidget(self.bt_add_build)
        self.bt_remove_build = QtWidgets.QToolButton(self.group_files)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.bt_remove_build.setIcon(icon)
        self.bt_remove_build.setObjectName("bt_remove_build")
        self.horizontalLayout_2.addWidget(self.bt_remove_build)
        self.line_2 = QtWidgets.QFrame(self.group_files)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.bt_move_build_up = QtWidgets.QToolButton(self.group_files)
        icon = QtGui.QIcon.fromTheme("go-up")
        self.bt_move_build_up.setIcon(icon)
        self.bt_move_build_up.setObjectName("bt_move_build_up")
        self.horizontalLayout_2.addWidget(self.bt_move_build_up)
        self.bt_move_build_down = QtWidgets.QToolButton(self.group_files)
        icon = QtGui.QIcon.fromTheme("go-down")
        self.bt_move_build_down.setIcon(icon)
        self.bt_move_build_down.setObjectName("bt_move_build_down")
        self.horizontalLayout_2.addWidget(self.bt_move_build_down)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.list_build = QtWidgets.QListWidget(self.group_files)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_build.sizePolicy().hasHeightForWidth())
        self.list_build.setSizePolicy(sizePolicy)
        self.list_build.setObjectName("list_build")
        self.verticalLayout_4.addWidget(self.list_build)
        self.horizontalLayout_8.addWidget(self.group_files)
        self.group_properties = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_properties.sizePolicy().hasHeightForWidth())
        self.group_properties.setSizePolicy(sizePolicy)
        self.group_properties.setObjectName("group_properties")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.group_properties)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.group_properties)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.combo_type = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_type.sizePolicy().hasHeightForWidth())
        self.combo_type.setSizePolicy(sizePolicy)
        self.combo_type.setObjectName("combo_type")
        self.combo_type.addItem("")
        self.combo_type.addItem("")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_type)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_3.setSpacing(9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.combo_standard = QtWidgets.QComboBox(self.tab)
        self.combo_standard.setObjectName("combo_standard")
        self.combo_standard.addItem("")
        self.combo_standard.addItem("")
        self.combo_standard.addItem("")
        self.combo_standard.addItem("")
        self.combo_standard.addItem("")
        self.combo_standard.addItem("")
        self.combo_standard.addItem("")
        self.combo_standard.addItem("")
        self.combo_standard.addItem("")
        self.combo_standard.addItem("")
        self.horizontalLayout_3.addWidget(self.combo_standard)
        self.cb_free_format = QtWidgets.QCheckBox(self.tab)
        self.cb_free_format.setObjectName("cb_free_format")
        self.horizontalLayout_3.addWidget(self.cb_free_format)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lbl_preparser_name = QtWidgets.QLabel(self.tab)
        self.lbl_preparser_name.setObjectName("lbl_preparser_name")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_preparser_name)
        self.cb_compile_submodules = QtWidgets.QCheckBox(self.tab)
        self.cb_compile_submodules.setObjectName("cb_compile_submodules")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cb_compile_submodules)
        self.verticalLayout_2.addLayout(self.formLayout_4)
        self.group_override_build_options = QtWidgets.QGroupBox(self.tab)
        self.group_override_build_options.setCheckable(True)
        self.group_override_build_options.setChecked(False)
        self.group_override_build_options.setObjectName("group_override_build_options")
        self.formLayout_2 = QtWidgets.QFormLayout(self.group_override_build_options)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_15 = QtWidgets.QLabel(self.group_override_build_options)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(0, 0, -1, -1)
        self.gridLayout_5.setHorizontalSpacing(9)
        self.gridLayout_5.setVerticalSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cb_ftrace = QtWidgets.QCheckBox(self.group_override_build_options)
        self.cb_ftrace.setObjectName("cb_ftrace")
        self.gridLayout_5.addWidget(self.cb_ftrace, 2, 0, 1, 1)
        self.cb_static = QtWidgets.QCheckBox(self.group_override_build_options)
        self.cb_static.setObjectName("cb_static")
        self.gridLayout_5.addWidget(self.cb_static, 0, 0, 1, 1)
        self.cb_debugging_line = QtWidgets.QCheckBox(self.group_override_build_options)
        self.cb_debugging_line.setObjectName("cb_debugging_line")
        self.gridLayout_5.addWidget(self.cb_debugging_line, 2, 2, 1, 1)
        self.cb_ftraceall = QtWidgets.QCheckBox(self.group_override_build_options)
        self.cb_ftraceall.setObjectName("cb_ftraceall")
        self.gridLayout_5.addWidget(self.cb_ftraceall, 2, 1, 1, 1)
        self.cb_debug = QtWidgets.QCheckBox(self.group_override_build_options)
        self.cb_debug.setObjectName("cb_debug")
        self.gridLayout_5.addWidget(self.cb_debug, 0, 1, 1, 1)
        self.cb_g = QtWidgets.QCheckBox(self.group_override_build_options)
        self.cb_g.setObjectName("cb_g")
        self.gridLayout_5.addWidget(self.cb_g, 0, 2, 1, 1)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.gridLayout_5)
        self.label_37 = QtWidgets.QLabel(self.group_override_build_options)
        self.label_37.setObjectName("label_37")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_12.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.list_copy_paths = QtWidgets.QListWidget(self.group_override_build_options)
        self.list_copy_paths.setObjectName("list_copy_paths")
        self.horizontalLayout_12.addWidget(self.list_copy_paths)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.bt_abs_copy_path = QtWidgets.QToolButton(self.group_override_build_options)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.bt_abs_copy_path.setIcon(icon)
        self.bt_abs_copy_path.setObjectName("bt_abs_copy_path")
        self.verticalLayout_12.addWidget(self.bt_abs_copy_path)
        self.bt_rel_copy_path = QtWidgets.QToolButton(self.group_override_build_options)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.bt_rel_copy_path.setIcon(icon)
        self.bt_rel_copy_path.setObjectName("bt_rel_copy_path")
        self.verticalLayout_12.addWidget(self.bt_rel_copy_path)
        self.bt_rm_copy_path = QtWidgets.QToolButton(self.group_override_build_options)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.bt_rm_copy_path.setIcon(icon)
        self.bt_rm_copy_path.setObjectName("bt_rm_copy_path")
        self.verticalLayout_12.addWidget(self.bt_rm_copy_path)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem1)
        self.horizontalLayout_12.addLayout(self.verticalLayout_12)
        self.horizontalLayout_12.setStretch(0, 1)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.label_17 = QtWidgets.QLabel(self.group_override_build_options)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_10.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.list_lib_paths = QtWidgets.QListWidget(self.group_override_build_options)
        self.list_lib_paths.setObjectName("list_lib_paths")
        self.horizontalLayout_10.addWidget(self.list_lib_paths)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.bt_abs_lib_path = QtWidgets.QToolButton(self.group_override_build_options)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.bt_abs_lib_path.setIcon(icon)
        self.bt_abs_lib_path.setObjectName("bt_abs_lib_path")
        self.verticalLayout_5.addWidget(self.bt_abs_lib_path)
        self.bt_rel_lib_path = QtWidgets.QToolButton(self.group_override_build_options)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.bt_rel_lib_path.setIcon(icon)
        self.bt_rel_lib_path.setObjectName("bt_rel_lib_path")
        self.verticalLayout_5.addWidget(self.bt_rel_lib_path)
        self.bt_delete_lib_path = QtWidgets.QToolButton(self.group_override_build_options)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.bt_delete_lib_path.setIcon(icon)
        self.bt_delete_lib_path.setObjectName("bt_delete_lib_path")
        self.verticalLayout_5.addWidget(self.bt_delete_lib_path)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.horizontalLayout_10.addLayout(self.verticalLayout_5)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.label_18 = QtWidgets.QLabel(self.group_override_build_options)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.edit_libs = QtWidgets.QLineEdit(self.group_override_build_options)
        self.edit_libs.setObjectName("edit_libs")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.edit_libs)
        self.label_35 = QtWidgets.QLabel(self.group_override_build_options)
        self.label_35.setObjectName("label_35")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.edit_extra_flags = QtWidgets.QLineEdit(self.group_override_build_options)
        self.edit_extra_flags.setObjectName("edit_extra_flags")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.edit_extra_flags)
        self.verticalLayout_2.addWidget(self.group_override_build_options)
        self.verticalLayout_2.setStretch(1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName("gridLayout")
        self.group_run = QtWidgets.QGroupBox(self.tab_2)
        self.group_run.setCheckable(True)
        self.group_run.setObjectName("group_run")
        self.formLayout_3 = QtWidgets.QFormLayout(self.group_run)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtWidgets.QLabel(self.group_run)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.edit_args = QtWidgets.QLineEdit(self.group_run)
        self.edit_args.setObjectName("edit_args")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_args)
        self.cb_external_term = QtWidgets.QCheckBox(self.group_run)
        self.cb_external_term.setObjectName("cb_external_term")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cb_external_term)
        self.label_5 = QtWidgets.QLabel(self.group_run)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.table_vars = QtWidgets.QTableWidget(self.group_run)
        self.table_vars.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.table_vars.setObjectName("table_vars")
        self.table_vars.setColumnCount(2)
        self.table_vars.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_vars.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_vars.setHorizontalHeaderItem(1, item)
        self.table_vars.horizontalHeader().setCascadingSectionResizes(True)
        self.table_vars.horizontalHeader().setStretchLastSection(True)
        self.table_vars.verticalHeader().setVisible(False)
        self.horizontalLayout_4.addWidget(self.table_vars)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bt_add_var = QtWidgets.QToolButton(self.group_run)
        self.bt_add_var.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.bt_add_var.setIcon(icon)
        self.bt_add_var.setObjectName("bt_add_var")
        self.verticalLayout_3.addWidget(self.bt_add_var)
        self.bt_rm_var = QtWidgets.QToolButton(self.group_run)
        self.bt_rm_var.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.bt_rm_var.setIcon(icon)
        self.bt_rm_var.setObjectName("bt_rm_var")
        self.verticalLayout_3.addWidget(self.bt_rm_var)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.formLayout_3.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.gridLayout.addWidget(self.group_run, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.group_properties)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        from hackedit.api.gettext import get_translation
        _ = get_translation(package="hackedit-cobol")
        Dialog.setWindowTitle(_("Project configuration"))
        self.label_2.setText(_("Main compiler:"))
        self.combo_compilers.setToolTip(_("Select the main compiler."))
        self.bt_secondary_compilers.setToolTip(_("Select secondary compiler that must be run when building the project/file."))
        self.bt_secondary_compilers.setText(_("Select secondary compiler(s)"))
        self.group_files.setTitle(_("Files"))
        self.bt_add_build.setToolTip(_("Add a file to the project build"))
        self.bt_add_build.setText(_("..."))
        self.bt_remove_build.setToolTip(_("Remove selected file"))
        self.bt_remove_build.setText(_("..."))
        self.bt_move_build_up.setToolTip(_("Move selected file up"))
        self.bt_move_build_up.setText(_("..."))
        self.bt_move_build_down.setToolTip(_("Move selected file down"))
        self.bt_move_build_down.setText(_("..."))
        self.list_build.setToolTip(_("The list of files to compile. \n"
"\n"
"The order in the list will determine the compile order."))
        self.group_properties.setTitle(_("Properties"))
        self.label_3.setText(_("File type:"))
        self.combo_type.setToolTip(_("Choose the file type: module or executable."))
        self.combo_type.setItemText(0, _("Executable"))
        self.combo_type.setItemText(1, _("Module"))
        self.label_8.setText(_("Standard:"))
        self.combo_standard.setToolTip(_("Choose the COBOL standard"))
        self.combo_standard.setItemText(0, _("default"))
        self.combo_standard.setItemText(1, _("cobol2002"))
        self.combo_standard.setItemText(2, _("cobol85"))
        self.combo_standard.setItemText(3, _("ibm"))
        self.combo_standard.setItemText(4, _("mvs"))
        self.combo_standard.setItemText(5, _("bs2000"))
        self.combo_standard.setItemText(6, _("mf"))
        self.combo_standard.setItemText(7, _("acu"))
        self.combo_standard.setItemText(8, _("cobol2014"))
        self.combo_standard.setItemText(9, _("none"))
        self.cb_free_format.setToolTip(_("<html><head/><body><p>Enable free format support.</p></body></html>"))
        self.cb_free_format.setText(_("Free format"))
        self.label_4.setText(_("Preparser:"))
        self.lbl_preparser_name.setText(_("None"))
        self.cb_compile_submodules.setToolTip(_("Check this to automatically detect and compile the submodules."))
        self.cb_compile_submodules.setText(_("Compile submodules automatically"))
        self.group_override_build_options.setToolTip(_("Setup custom options. If unchecked, the default options of the selected compiler configuration will be applied."))
        self.group_override_build_options.setTitle(_("Override defau&lt options"))
        self.label_15.setText(_("Compiler flags:"))
        self.cb_ftrace.setToolTip(_("<html><head/><body><p>Generate trace code</p><p>   - Executed SECTION/PARAGRAPH</p></body></html>"))
        self.cb_ftrace.setText(_("-ftrace"))
        self.cb_static.setToolTip(_("Link statically"))
        self.cb_static.setText(_("-static"))
        self.cb_debugging_line.setToolTip(_("<html><head/><body><p>Enable debugging lines</p><p>  - \'D\' in indicator column or floating &gt;&gt;D</p></body></html>"))
        self.cb_debugging_line.setText(_("-fdebugging-line"))
        self.cb_ftraceall.setToolTip(_("<html><head/><body><p>Generate trace code</p><p>  - Executed SECTION/PARAGRAPH/STATEMENTS</p><p>  - Turned on by -debug</p></body></html>"))
        self.cb_ftraceall.setText(_("-ftraceall"))
        self.cb_debug.setToolTip(_("Enable all run-time error checking\n"
""))
        self.cb_debug.setText(_("-debug"))
        self.cb_g.setToolTip(_("Enable C compiler debug / stack check / trace"))
        self.cb_g.setText(_("-g"))
        self.label_37.setText(_("Copybook paths:"))
        self.list_copy_paths.setToolTip(_("The list of copybook paths."))
        self.bt_abs_copy_path.setToolTip(_("Add an absolute copybook path"))
        self.bt_abs_copy_path.setText(_("..."))
        self.bt_rel_copy_path.setToolTip(_("Add a relative copybook path"))
        self.bt_rel_copy_path.setText(_("..."))
        self.bt_rm_copy_path.setToolTip(_("Delete selected path"))
        self.bt_rm_copy_path.setText(_("..."))
        self.label_17.setText(_("Library paths:"))
        self.list_lib_paths.setToolTip(_("<html><head/><body><p>The list of library paths.</p></body></html>"))
        self.bt_abs_lib_path.setToolTip(_("Add an absolute library path"))
        self.bt_abs_lib_path.setText(_("..."))
        self.bt_rel_lib_path.setToolTip(_("Add a relative library path"))
        self.bt_rel_lib_path.setText(_("..."))
        self.bt_delete_lib_path.setToolTip(_("Delete selected path"))
        self.bt_delete_lib_path.setText(_("..."))
        self.label_18.setText(_("Libraries:"))
        self.edit_libs.setToolTip(_("<html><head/><body><p>The list of  libraries you would like your programs to link with (-l option).</p><p>Each entry in the list must be separated by a semi-colon.</p></body></html>"))
        self.label_35.setText(_("Extra compiler flags:"))
        self.edit_extra_flags.setToolTip(_("<html><head/><body><p>List of extra compiler flags. Each entry in the list must be separated by a semi-colon (;).</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _("Build options"))
        self.group_run.setToolTip(_("<html><head/><body><p>Enable/Disable run. </p><p>If checked, the result of the compilation of this file can be run and a corresponding entry will appear in the run configurations menu. </p><p>This is enabled by default for all executables but you can also enable it for modules. In that case the module will be run using <span style=\" font-weight:600;\">cobcrun.</span></p></body></html>"))
        self.group_run.setTitle(_("Runnab&le"))
        self.label.setText(_("Arguments:"))
        self.edit_args.setToolTip(_("The list of arguments to pass to the executable"))
        self.cb_external_term.setToolTip(_("Run executable in an external terminal. Check this if you\'re using the SCREEN SECTION or some advanced ACCEPT/DISPLAY extensions."))
        self.cb_external_term.setText(_("Run in external terminal"))
        self.label_5.setText(_("Environment:"))
        self.table_vars.setToolTip(_("The list of enviromnent variables to set on the process that is being run."))
        item = self.table_vars.horizontalHeaderItem(0)
        item.setText(_("Key"))
        item = self.table_vars.horizontalHeaderItem(1)
        item.setText(_("Value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _("Run options"))

