# Example build requirements folling build-deps-pep
[build-system]
requires = ["pytoml>=0.1", "enscons"]

[tool.enscons]
name="enscons"
version="0.0.1"
packages=['enscons']
install_requires=['import_scons']
description="Tools for building Python packages with SCons"
description_file="README"
license="MIT"
classifiers=[
  "Programming Language :: Python :: 2.7",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.4",
  "Programming Language :: Python :: 3.5",
]
keywords=["packaging", "wheel"]
author="Daniel Holth"
author_email="dholth@fastmail.fm"
url="https://bitbucket.org/dholth/enscons"

[tool.enscons.extras_require]
doc = ['sphinx']
