
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "86b3155b3517c1633f69a88b6408efecc18b6c4c",
 "version": "0.5.post11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
