sudo: false
language: python
python:
- 2.7
- 3.5
script:
- pip install -U pytest
- python setup.py test
deploy:
  provider: pypi
  on:
    tags: true
    all_branches: true
    python: 3.5
  user: jaraco
  distributions: release
  password:
    secure: g3YRlcDwloi+Gg2+y/FDhmkgHD1nMiq1l1QAe5efCI9ZxZJWLWjX/z+OiaYTd96iK5UXnx4y6AevAJunvafC9AbzO1I19TrkJjGgxL91fhheVUwkRn8txCNuKbnr3pa9l053MnPIifXwSaSfm25VsS3/tyM5u4D4KQHoLdGy0eY5WR9/bMjkwfDB9EpB4f45N1Y7EAn1fEv4hldCMhtUV6SnNyJTVfDJcON1y+XCrvw+glXd9JLeHcJsX9unFsOdPYkH9ev0RD1x8zjFVj/dBRSR+Y2+AFcrQyHUAG/McrS3uYGacc9Qn0La0UvzWrj+2dxvisu8C2yMod6GBSW61eMu3q0LTUBd2OXMx47eRMerI5jnjohK+477PV9KBczIE4QSwPKe0h0bSuUHGFsB9JzYrRNTqwJeKdXFIVoOZvDooOTkT7zWepFYRCCe3xGoiGNg8TWGrr3qnVSEeRiJ1xdwjVYHAIPq19XIWvYydeJaGYAHQnT6koprKV7mRb4/wl9MUsNVBy0ZuhUgZy6ePC6cEZavpIbJPMlgzEQlC7Qj0GAFTSWi6j4I2qpe5dC1HLl95W7A1MN8rD/yFY3DzeBgv9cgRDvMJwxWF8CKz61dIv5F07tTIgQAZlqIwmZLOQwshNWgV4rcUe+kGkpFNmNPjOPor6fgstEbmC5Gdio=
