
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "8b548b9eb3cc21df22c33e450f910bb0ec7fb095",
 "version": "0.post.dev128"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
