
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "286ab2098980fa643f400908c97bbc83abe14bc1",
 "version": "0.post.dev229"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
