
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "9f073b72aa5b6af37f0adb4a112253c3f761cd24",
 "version": "1.6.2rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
