
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.11.0'
version_full = 'bb25ba4f07b4b6ba8242fe6d82aa66601ddf7e14'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

