novaideo:
  restart: always
  build: .
  environment:
    - SECRET=mybigsecret
    - APPLICATION_URL=https://participate.nova-ideo.org
    - MAIL_DEFAULT_SENDER=noreply@nova-ideo.org
    - TIMEOUT=3600
  volumes:
    - ./var:/app/var
    - ./cache:/app/cache
  external_links:
    - postfix:mail
nginx:
  restart: always
  image: nginx
  volumes:
    - ./nginx-app-prod.conf:/etc/nginx/conf.d/app.conf:ro
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./html:/etc/nginx/html:ro
    - ./tls:/etc/nginx/tls:ro
  ports:
    - "80:80"
    - "443:443"
  links:
    - novaideo:app
