
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3109dcdaa2cf27ed8bfa8f15447d79fc3e4a77c7",
 "version": "0.post.dev249"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
