language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
    - nasm
sudo: false
install:
  - pip install -U setuptools pip
  - pip install -U py pytest
  - pip install --no-binary capstone -e .[disasm,rop,ssh]
script:
  - python setup.py test
