
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "aa8bcd93eab6bde154cca9b9c353496ec2f6492e",
 "version": "1.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
