package:
  name: libastra
  version: '1.8b'

source:
  git_url: https://github.com/astra-toolbox/astra-toolbox.git
  #git_tag: v1.7.1 # Change to 1.8 after release

build:
  number: 0
  script_env:
    - CUDA_ROOT
    - MAKEOPTS

about:
  home: http://www.astra-toolbox.com
  license: GPLv3
  summary: 'The ASTRA Toolbox is a Python toolbox of high-performance GPU primitives for 2D and 3D tomography.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
