
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "ec11927cc031fbf57197b80e59be67e0f7fad007",
 "version": "0.post.dev217"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
