language: python
matrix:
  include:
    - python: "2.7"
      env: TOX_ENV=py27_dj18
    - python: "3.4"
      env: TOX_ENV=py34_dj18
    - python: "2.7"
      env: TOX_ENV=py27_dj19
    - python: "3.4"
      env: TOX_ENV=py34_dj19
    - python: "3.5"
      env: TOX_ENV=py35_dj19
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
sudo: false
