    - apt: pkg={{item}} force=yes state=installed  
      with_items:
       - wget
       - build-essential
       - python-pip
       
    - apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
  
    - apt_repository: repo='{{item}}' state=absent update_cache=true
      with_items: 
       - deb http://dl.google.com/linux/chrome/deb/ stable main
       - ppa:aacebedo/libi3ipc-glib
       - ppa:aacebedo/xfce4-i3-workspaces-plugin
       - ppa:aacebedo/fasd
       
    - get_url: url=https://github.com/clvv/fasd/archive/1.0.1.tar.gz dest=/tmp/fasd.tar.gz
    - unarchive: src=/tmp/fasd.tar.gz dest=/tmp/
    - shell: make uninstall chdir=/tmp/fasd-1.0.1

    - file: path=/usr/local/bin/j4-dmenu-desktop state=absent
    
    - pip: name={{item}} state=absent
      with_items:
       - albert
       - pathlib
       - psutil
       - thefuck
       - i3-py
       - quickswitch-i3
       - cheat
       
    - file: path=/home/{{remote_user}}/.i3 state=absent 
    
    - apt: pkg={{item}} force=yes state=absent  
      with_items:
       - aptitude
       - docker.io
       - vim
       - python-dev
       - conky
       - wget
       - cmake
       - build-essential
       - google-chrome-beta
       - python-pip
       - dmenu
       - feh  
       - git
       - python-software-properties
       - git-flow
       - libi3ipc-glib
       - xfce4-i3-workspaces-plugin
       - fasd
