# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('permabots', '0006_auto_20160505_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
                ('callback_id', models.CharField(db_index=True, max_length=255, verbose_name='Id')),
                ('data', models.TextField(blank=True, max_length=255, null=True, verbose_name='Data')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='callback_queries', to='permabots.User', verbose_name='User')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='callback_queries', to='permabots.Message', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'CallbackQuery',
                'verbose_name_plural': 'CallbackQueries',
            },
        ),
        migrations.AddField(
            model_name='update',
            name='callback_query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='permabots.CallbackQuery', verbose_name='Callback Query'),
        ),
    ]
