
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a96f8f59da7af94069c467c3d1a0772b7fafd77a",
 "version": "0.post.dev203"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
