package:
  name: libcpptraj-dev
  version: 4.2.5

source:
  git_url: https://github.com/amber-md/cpptraj.git
  git_tag: master

requirements:
  build:
    - libnetcdf
    - zlib
    - bzip2
  run:
    - libnetcdf
    - zlib
    - bzip2

about:
    home: https://github.com/amber-md/cpptraj/
    license: GNU
    summary: libcpptraj
