language: python
sudo: false
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5
    - pypy
install:
    - pip install .
    - pip install zope.security
script:
    - python setup.py test -q
notifications:
    email: false
