
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1a0fe6d776c5ffe810e2d5f5b3b6c37bb515e784",
 "version": "0.post.dev237"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
