package:
  name: easyaccess
  version: "1.3.0rc"

source:
  fn: easyaccess-1.3.0-rc2.tar.gz
  md5: dbc19f823613ef1fbc35f6cc17ca0262
  url: https://pypi.python.org/packages/4c/4b/65e0d4b95ed47295d8593c6b6c19d4e7a99eba3f4ae7857ea8f56d101b9c/easyaccess-1.3.0-rc2.tar.gz
  #git_rev: '1.2.1b'
  #git_url: https://github.com/mgckind/easyaccess
  

build:
  number: 2


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - future
    - termcolor
    - fitsio
    - pandas >=0.14
    - oracle-instantclient
    - cx_oracle

test:
  # Python imports
  imports:
    - easyaccess

about:
  home: https://github.com/mgckind/easyaccess
  license: University of Illinois/NCSA Open Source License
  summary: 'Python command line interpreter to access DES Oracle database'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
