
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "0017db7e53d2c4846289bb6ee07d554772c10327",
 "version": "0.3.post6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
