
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '807047B8ADAD11E31FDE2580395CA1CB'
    
_lr_action_items = {'OPEN_DASH':([0,2,4,5,6,8,15,19,21,],[7,-15,7,7,7,-16,-8,-9,-7,]),'WORD':([0,2,3,4,5,6,7,8,9,10,15,16,18,19,21,23,25,],[2,2,9,2,2,2,9,-16,-10,16,-8,-14,16,-9,-7,2,-13,]),'OPEN':([0,2,4,5,6,8,15,19,21,],[3,-15,3,3,3,-16,-8,-9,-7,]),'QUOTE':([2,8,20,24,],[-15,-16,23,25,]),'ASSIGN':([16,],[20,]),'CLOSE':([9,10,14,16,17,18,22,25,],[-10,15,19,-14,21,-11,-12,-13,]),'$end':([1,2,4,5,6,8,11,12,13,15,19,21,],[0,-15,-1,-2,-3,-16,-5,-6,-4,-8,-9,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'attribute':([10,18,],[18,18,]),'element':([0,4,5,6,],[1,11,12,13,]),'attributes':([10,18,],[17,22,]),'tag':([0,4,5,6,],[4,4,4,4,]),'content':([0,2,4,5,6,23,],[5,8,5,5,5,24,]),'close_tag':([0,4,5,6,],[6,6,6,6,]),'tagname':([3,7,],[10,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> element","S'",1,None,None,None),
  ('element -> tag','element',1,'p_element','parser.py',58),
  ('element -> content','element',1,'p_element','parser.py',59),
  ('element -> close_tag','element',1,'p_element','parser.py',60),
  ('element -> close_tag element','element',2,'p_element','parser.py',61),
  ('element -> tag element','element',2,'p_element','parser.py',62),
  ('element -> content element','element',2,'p_element','parser.py',63),
  ('tag -> OPEN tagname attributes CLOSE','tag',4,'p_tag','parser.py',67),
  ('tag -> OPEN tagname CLOSE','tag',3,'p_tag','parser.py',68),
  ('close_tag -> OPEN_DASH tagname CLOSE','close_tag',3,'p_close_tag','parser.py',78),
  ('tagname -> WORD','tagname',1,'p_tagname','parser.py',84),
  ('attributes -> attribute','attributes',1,'p_attributes','parser.py',88),
  ('attributes -> attribute attributes','attributes',2,'p_attributes','parser.py',89),
  ('attribute -> WORD ASSIGN QUOTE content QUOTE','attribute',5,'p_attribute','parser.py',97),
  ('attribute -> WORD','attribute',1,'p_attribute','parser.py',98),
  ('content -> WORD','content',1,'p_content','parser.py',105),
  ('content -> WORD content','content',2,'p_content','parser.py',106),
]
