---
#default vairables use for setting up myria-python
myria_python_repository_url: 'https://github.com/uwescience/myria-python.git'
myria_python_path: '{{data_vol_mount_dir}}/myria-python'
myria_python_branch: master
