# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from coquery.gui.pyqt_compat import QtCore, QtGui, frameShadow, frameShape

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName(_fromUtf8("SettingsDialog"))
        SettingsDialog.resize(640, 480)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsDialog.sizePolicy().hasHeightForWidth())
        SettingsDialog.setSizePolicy(sizePolicy)
        self.verticalLayout_3 = QtGui.QVBoxLayout(SettingsDialog)
        self.verticalLayout_3.setContentsMargins(4, -1, 4, -1)
        self.verticalLayout_3.setSpacing(8)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(SettingsDialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_sample_context = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sample_context.sizePolicy().hasHeightForWidth())
        self.label_sample_context.setSizePolicy(sizePolicy)
        self.label_sample_context.setFrameShape(frameShape)
        self.label_sample_context.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sample_context.setObjectName(_fromUtf8("label_sample_context"))
        self.gridLayout.addWidget(self.label_sample_context, 1, 1, 1, 1)
        self.button_figure_font = QtGui.QPushButton(self.tab)
        self.button_figure_font.setObjectName(_fromUtf8("button_figure_font"))
        self.gridLayout.addWidget(self.button_figure_font, 2, 2, 1, 1)
        self.button_reset_table = QtGui.QPushButton(self.tab)
        self.button_reset_table.setObjectName(_fromUtf8("button_reset_table"))
        self.gridLayout.addWidget(self.button_reset_table, 0, 3, 1, 1)
        self.button_reset_context = QtGui.QPushButton(self.tab)
        self.button_reset_context.setObjectName(_fromUtf8("button_reset_context"))
        self.gridLayout.addWidget(self.button_reset_context, 1, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.button_context_font = QtGui.QPushButton(self.tab)
        self.button_context_font.setObjectName(_fromUtf8("button_context_font"))
        self.gridLayout.addWidget(self.button_context_font, 1, 2, 1, 1)
        self.button_reset_figure = QtGui.QPushButton(self.tab)
        self.button_reset_figure.setObjectName(_fromUtf8("button_reset_figure"))
        self.gridLayout.addWidget(self.button_reset_figure, 2, 3, 1, 1)
        self.label_sample_table = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sample_table.sizePolicy().hasHeightForWidth())
        self.label_sample_table.setSizePolicy(sizePolicy)
        self.label_sample_table.setFrameShape(frameShape)
        self.label_sample_table.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sample_table.setObjectName(_fromUtf8("label_sample_table"))
        self.gridLayout.addWidget(self.label_sample_table, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.button_table_font = QtGui.QPushButton(self.tab)
        self.button_table_font.setObjectName(_fromUtf8("button_table_font"))
        self.gridLayout.addWidget(self.button_table_font, 0, 2, 1, 1)
        self.label_sample_figure = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sample_figure.sizePolicy().hasHeightForWidth())
        self.label_sample_figure.setSizePolicy(sizePolicy)
        self.label_sample_figure.setFrameShape(frameShape)
        self.label_sample_figure.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_sample_figure.setObjectName(_fromUtf8("label_sample_figure"))
        self.gridLayout.addWidget(self.label_sample_figure, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(3, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.group_case = QtGui.QGroupBox(self.tab_2)
        self.group_case.setObjectName(_fromUtf8("group_case"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.group_case)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.radio_output_case_leave = QtGui.QRadioButton(self.group_case)
        self.radio_output_case_leave.setObjectName(_fromUtf8("radio_output_case_leave"))
        self.verticalLayout_4.addWidget(self.radio_output_case_leave)
        self.radio_output_case_lower = QtGui.QRadioButton(self.group_case)
        self.radio_output_case_lower.setObjectName(_fromUtf8("radio_output_case_lower"))
        self.verticalLayout_4.addWidget(self.radio_output_case_lower)
        self.radio_output_case_upper = QtGui.QRadioButton(self.group_case)
        self.radio_output_case_upper.setObjectName(_fromUtf8("radio_output_case_upper"))
        self.verticalLayout_4.addWidget(self.radio_output_case_upper)
        self.verticalLayout.addWidget(self.group_case)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.spin_digits = QtGui.QSpinBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_digits.sizePolicy().hasHeightForWidth())
        self.spin_digits.setSizePolicy(sizePolicy)
        self.spin_digits.setProperty("value", 3)
        self.spin_digits.setObjectName(_fromUtf8("spin_digits"))
        self.horizontalLayout.addWidget(self.spin_digits)
        self.label_7 = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout.addWidget(self.label_7)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.check_align_quantified = QtGui.QCheckBox(self.tab_2)
        self.check_align_quantified.setObjectName(_fromUtf8("check_align_quantified"))
        self.verticalLayout.addWidget(self.check_align_quantified)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.check_ask_on_quit = QtGui.QCheckBox(self.tab_3)
        self.check_ask_on_quit.setObjectName(_fromUtf8("check_ask_on_quit"))
        self.verticalLayout_5.addWidget(self.check_ask_on_quit)
        self.check_save_query_string = QtGui.QCheckBox(self.tab_3)
        self.check_save_query_string.setObjectName(_fromUtf8("check_save_query_string"))
        self.verticalLayout_5.addWidget(self.check_save_query_string)
        self.check_save_query_file = QtGui.QCheckBox(self.tab_3)
        self.check_save_query_file.setObjectName(_fromUtf8("check_save_query_file"))
        self.verticalLayout_5.addWidget(self.check_save_query_file)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.group_paths = QtGui.QGroupBox(self.tab_4)
        self.group_paths.setObjectName(_fromUtf8("group_paths"))
        self.gridLayout_2 = QtGui.QGridLayout(self.group_paths)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_8 = QtGui.QLabel(self.group_paths)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.edit_installer_path = QtGui.QLineEdit(self.group_paths)
        self.edit_installer_path.setObjectName(_fromUtf8("edit_installer_path"))
        self.gridLayout_2.addWidget(self.edit_installer_path, 0, 1, 1, 1)
        self.button_installer_path = QtGui.QPushButton(self.group_paths)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_installer_path.sizePolicy().hasHeightForWidth())
        self.button_installer_path.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("folder"))
        self.button_installer_path.setIcon(icon)
        self.button_installer_path.setObjectName(_fromUtf8("button_installer_path"))
        self.gridLayout_2.addWidget(self.button_installer_path, 0, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.group_paths)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.edit_visualizer_path = QtGui.QLineEdit(self.group_paths)
        self.edit_visualizer_path.setObjectName(_fromUtf8("edit_visualizer_path"))
        self.gridLayout_2.addWidget(self.edit_visualizer_path, 1, 1, 1, 1)
        self.button_visualizer_path = QtGui.QPushButton(self.group_paths)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_visualizer_path.sizePolicy().hasHeightForWidth())
        self.button_visualizer_path.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("folder"))
        self.button_visualizer_path.setIcon(icon)
        self.button_visualizer_path.setObjectName(_fromUtf8("button_visualizer_path"))
        self.gridLayout_2.addWidget(self.button_visualizer_path, 1, 2, 1, 1)
        self.verticalLayout_6.addWidget(self.group_paths)
        self.check_ignore_case_query = QtGui.QCheckBox(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_ignore_case_query.sizePolicy().hasHeightForWidth())
        self.check_ignore_case_query.setSizePolicy(sizePolicy)
        self.check_ignore_case_query.setObjectName(_fromUtf8("check_ignore_case_query"))
        self.verticalLayout_6.addWidget(self.check_ignore_case_query)
        spacerItem4 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(SettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_3.addWidget(self.buttonBox)
        self.tabWidget.raise_()
        self.buttonBox.raise_()
        self.label_3.setBuddy(self.spin_digits)

        self.retranslateUi(SettingsDialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SettingsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings – Coquery", None))
        self.label_5.setText(_translate("SettingsDialog", "Context font:", None))
        self.label_sample_context.setText(_translate("SettingsDialog", "TextLabel", None))
        self.button_figure_font.setText(_translate("SettingsDialog", "Change...", None))
        self.button_reset_table.setText(_translate("SettingsDialog", "Reset", None))
        self.button_reset_context.setText(_translate("SettingsDialog", "Reset", None))
        self.label_6.setText(_translate("SettingsDialog", "Default figure font:", None))
        self.button_context_font.setText(_translate("SettingsDialog", "Change...", None))
        self.button_reset_figure.setText(_translate("SettingsDialog", "Reset", None))
        self.label_sample_table.setText(_translate("SettingsDialog", "TextLabel", None))
        self.label_4.setText(_translate("SettingsDialog", "Table font:", None))
        self.button_table_font.setText(_translate("SettingsDialog", "Change...", None))
        self.label_sample_figure.setText(_translate("SettingsDialog", "TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SettingsDialog", "Fonts", None))
        self.group_case.setTitle(_translate("SettingsDialog", "Case", None))
        self.radio_output_case_leave.setText(_translate("SettingsDialog", "Do not change case", None))
        self.radio_output_case_lower.setText(_translate("SettingsDialog", "Lower case", None))
        self.radio_output_case_upper.setText(_translate("SettingsDialog", "Upper case", None))
        self.label_3.setText(_translate("SettingsDialog", "&Display ", None))
        self.spin_digits.setSuffix(_translate("SettingsDialog", " digit(s)", None))
        self.label_7.setText(_translate("SettingsDialog", "after decimal point", None))
        self.check_align_quantified.setText(_translate("SettingsDialog", "Align &quantified token columns", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SettingsDialog", "Results table", None))
        self.check_ask_on_quit.setText(_translate("SettingsDialog", "Ask if &unsaved results should be saved upon exit", None))
        self.check_save_query_string.setText(_translate("SettingsDialog", "Save last query &string in configuration file", None))
        self.check_save_query_file.setText(_translate("SettingsDialog", "Save last query &file in configuration file", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SettingsDialog", "Quitting", None))
        self.group_paths.setTitle(_translate("SettingsDialog", "Additional paths", None))
        self.label_8.setText(_translate("SettingsDialog", "Corpus &installers: ", None))
        self.button_installer_path.setText(_translate("SettingsDialog", "&Browse", None))
        self.button_installer_path.setShortcut(_translate("SettingsDialog", "Alt+B", None))
        self.label_9.setText(_translate("SettingsDialog", "&Visualizers:", None))
        self.button_visualizer_path.setText(_translate("SettingsDialog", "B&rowse", None))
        self.button_visualizer_path.setShortcut(_translate("SettingsDialog", "Alt+B", None))
        self.check_ignore_case_query.setText(_translate("SettingsDialog", "Ignore case in query strings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("SettingsDialog", "Other", None))


