sudo: false
language: python
python: 3.5
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pypy

script:
  - python -m pip install setuptools pip -U
  - ./bin/test_standalone.sh
  - pip install tox
  - tox -e $TOX_ENV

branches:
  except:
    - standalone
