# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coquery.ui'
#
# Created: Mon Mar  7 19:22:38 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from coquery.gui.pyqt_compat import QtCore, QtGui, frameShadow, frameShape

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(805, 727)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setContentsMargins(6, 2, 6, 2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.splitter_2 = QtGui.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setOpaqueResize(True)
        self.splitter_2.setHandleWidth(4)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.options_area = QtGui.QFrame(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.options_area.sizePolicy().hasHeightForWidth())
        self.options_area.setSizePolicy(sizePolicy)
        self.options_area.setObjectName(_fromUtf8("options_area"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.options_area)
        self.horizontalLayout_7.setSpacing(12)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 8)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.widget = QtGui.QWidget(self.options_area)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.box_corpus_select = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_corpus_select.sizePolicy().hasHeightForWidth())
        self.box_corpus_select.setSizePolicy(sizePolicy)
        self.box_corpus_select.setObjectName(_fromUtf8("box_corpus_select"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.box_corpus_select)
        self.verticalLayout_5.setContentsMargins(8, -1, 8, -1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.combo_corpus = QtGui.QComboBox(self.box_corpus_select)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_corpus.sizePolicy().hasHeightForWidth())
        self.combo_corpus.setSizePolicy(sizePolicy)
        self.combo_corpus.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.combo_corpus.setEditable(False)
        self.combo_corpus.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.combo_corpus.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.combo_corpus.setFrame(True)
        self.combo_corpus.setObjectName(_fromUtf8("combo_corpus"))
        self.verticalLayout_5.addWidget(self.combo_corpus)
        self.verticalLayout_3.addWidget(self.box_corpus_select)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem)
        self.box_context_mode = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_context_mode.sizePolicy().hasHeightForWidth())
        self.box_context_mode.setSizePolicy(sizePolicy)
        self.box_context_mode.setObjectName(_fromUtf8("box_context_mode"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.box_context_mode)
        self.verticalLayout_8.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.verticalLayout_8.setContentsMargins(8, -1, 8, -1)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.radio_context_none = QtGui.QRadioButton(self.box_context_mode)
        self.radio_context_none.setStyleSheet(_fromUtf8("text-align: center center"))
        self.radio_context_none.setObjectName(_fromUtf8("radio_context_none"))
        self.verticalLayout_7.addWidget(self.radio_context_none)
        self.radio_context_mode_kwic = QtGui.QRadioButton(self.box_context_mode)
        self.radio_context_mode_kwic.setStyleSheet(_fromUtf8("text-align: center center"))
        self.radio_context_mode_kwic.setObjectName(_fromUtf8("radio_context_mode_kwic"))
        self.verticalLayout_7.addWidget(self.radio_context_mode_kwic)
        self.radio_context_mode_string = QtGui.QRadioButton(self.box_context_mode)
        self.radio_context_mode_string.setStyleSheet(_fromUtf8("text-align: center center"))
        self.radio_context_mode_string.setObjectName(_fromUtf8("radio_context_mode_string"))
        self.verticalLayout_7.addWidget(self.radio_context_mode_string)
        self.radio_context_mode_columns = QtGui.QRadioButton(self.box_context_mode)
        self.radio_context_mode_columns.setStyleSheet(_fromUtf8("text-align: center center"))
        self.radio_context_mode_columns.setObjectName(_fromUtf8("radio_context_mode_columns"))
        self.verticalLayout_7.addWidget(self.radio_context_mode_columns)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.context_frame = QtGui.QFrame(self.box_context_mode)
        self.context_frame.setLineWidth(0)
        self.context_frame.setObjectName(_fromUtf8("context_frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.context_frame)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.context_left_span = QtGui.QSpinBox(self.context_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_left_span.sizePolicy().hasHeightForWidth())
        self.context_left_span.setSizePolicy(sizePolicy)
        self.context_left_span.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.context_left_span.setSuffix(_fromUtf8(""))
        self.context_left_span.setObjectName(_fromUtf8("context_left_span"))
        self.horizontalLayout.addWidget(self.context_left_span)
        self.context_right_span = QtGui.QSpinBox(self.context_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.context_right_span.sizePolicy().hasHeightForWidth())
        self.context_right_span.setSizePolicy(sizePolicy)
        self.context_right_span.setFrame(True)
        self.context_right_span.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.context_right_span.setSuffix(_fromUtf8(""))
        self.context_right_span.setObjectName(_fromUtf8("context_right_span"))
        self.horizontalLayout.addWidget(self.context_right_span)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_8.addWidget(self.context_frame)
        self.verticalLayout_3.addWidget(self.box_context_mode)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.frame_buttons = QtGui.QFrame(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_buttons.sizePolicy().hasHeightForWidth())
        self.frame_buttons.setSizePolicy(sizePolicy)
        self.frame_buttons.setObjectName(_fromUtf8("frame_buttons"))
        self.box_buttons = QtGui.QGridLayout(self.frame_buttons)
        self.box_buttons.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.box_buttons.setMargin(0)
        self.box_buttons.setHorizontalSpacing(8)
        self.box_buttons.setVerticalSpacing(0)
        self.box_buttons.setObjectName(_fromUtf8("box_buttons"))
        self.button_filters = QtGui.QPushButton(self.frame_buttons)
        self.button_filters.setObjectName(_fromUtf8("button_filters"))
        self.box_buttons.addWidget(self.button_filters, 1, 0, 1, 1)
        self.button_stopwords = QtGui.QPushButton(self.frame_buttons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_stopwords.sizePolicy().hasHeightForWidth())
        self.button_stopwords.setSizePolicy(sizePolicy)
        self.button_stopwords.setObjectName(_fromUtf8("button_stopwords"))
        self.box_buttons.addWidget(self.button_stopwords, 2, 0, 1, 1)
        self.stopword_layout = QtGui.QHBoxLayout()
        self.stopword_layout.setObjectName(_fromUtf8("stopword_layout"))
        self.box_buttons.addLayout(self.stopword_layout, 2, 1, 1, 1)
        self.button_run_query = QtGui.QPushButton(self.frame_buttons)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_run_query.sizePolicy().hasHeightForWidth())
        self.button_run_query.setSizePolicy(sizePolicy)
        self.button_run_query.setAutoDefault(False)
        self.button_run_query.setDefault(True)
        self.button_run_query.setObjectName(_fromUtf8("button_run_query"))
        self.box_buttons.addWidget(self.button_run_query, 3, 0, 1, 1)
        self.filter_layout = QtGui.QHBoxLayout()
        self.filter_layout.setObjectName(_fromUtf8("filter_layout"))
        self.box_buttons.addLayout(self.filter_layout, 1, 1, 1, 1)
        self.query_layout = QtGui.QHBoxLayout()
        self.query_layout.setObjectName(_fromUtf8("query_layout"))
        self.box_buttons.addLayout(self.query_layout, 3, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(32, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.box_buttons.addItem(spacerItem2, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_buttons)
        self.horizontalLayout_7.addWidget(self.widget)
        self.box_input_settings = QtGui.QGroupBox(self.options_area)
        self.box_input_settings.setObjectName(_fromUtf8("box_input_settings"))
        self.layout_query = QtGui.QGridLayout(self.box_input_settings)
        self.layout_query.setObjectName(_fromUtf8("layout_query"))
        self.radio_query_string = QtGui.QRadioButton(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_query_string.sizePolicy().hasHeightForWidth())
        self.radio_query_string.setSizePolicy(sizePolicy)
        self.radio_query_string.setText(_fromUtf8(""))
        self.radio_query_string.setChecked(True)
        self.radio_query_string.setObjectName(_fromUtf8("radio_query_string"))
        self.layout_query.addWidget(self.radio_query_string, 0, 0, 1, 1)
        self.edit_query_string = QtGui.QTextEdit(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_query_string.sizePolicy().hasHeightForWidth())
        self.edit_query_string.setSizePolicy(sizePolicy)
        self.edit_query_string.setObjectName(_fromUtf8("edit_query_string"))
        self.layout_query.addWidget(self.edit_query_string, 0, 1, 1, 2)
        self.radio_query_file = QtGui.QRadioButton(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_query_file.sizePolicy().hasHeightForWidth())
        self.radio_query_file.setSizePolicy(sizePolicy)
        self.radio_query_file.setText(_fromUtf8(""))
        self.radio_query_file.setObjectName(_fromUtf8("radio_query_file"))
        self.layout_query.addWidget(self.radio_query_file, 1, 0, 2, 1)
        self.button_browse_file = QtGui.QPushButton(self.box_input_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_browse_file.sizePolicy().hasHeightForWidth())
        self.button_browse_file.setSizePolicy(sizePolicy)
        self.button_browse_file.setObjectName(_fromUtf8("button_browse_file"))
        self.layout_query.addWidget(self.button_browse_file, 1, 2, 1, 1)
        self.button_file_options = QtGui.QPushButton(self.box_input_settings)
        self.button_file_options.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_file_options.sizePolicy().hasHeightForWidth())
        self.button_file_options.setSizePolicy(sizePolicy)
        self.button_file_options.setObjectName(_fromUtf8("button_file_options"))
        self.layout_query.addWidget(self.button_file_options, 2, 2, 1, 1)
        self.edit_file_name = QtGui.QLineEdit(self.box_input_settings)
        self.edit_file_name.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_file_name.sizePolicy().hasHeightForWidth())
        self.edit_file_name.setSizePolicy(sizePolicy)
        self.edit_file_name.setAccessibleDescription(_fromUtf8(""))
        self.edit_file_name.setObjectName(_fromUtf8("edit_file_name"))
        self.layout_query.addWidget(self.edit_file_name, 1, 1, 1, 1)
        self.horizontalLayout_7.addWidget(self.box_input_settings)
        self.box_output_options = QtGui.QGroupBox(self.options_area)
        self.box_output_options.setObjectName(_fromUtf8("box_output_options"))
        self.output_columns = QtGui.QVBoxLayout(self.box_output_options)
        self.output_columns.setSpacing(0)
        self.output_columns.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.output_columns.setContentsMargins(8, -1, 8, 6)
        self.output_columns.setObjectName(_fromUtf8("output_columns"))
        self.horizontalLayout_7.addWidget(self.box_output_options)
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(4)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.data_preview = QtGui.QTableView(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_preview.sizePolicy().hasHeightForWidth())
        self.data_preview.setSizePolicy(sizePolicy)
        self.data_preview.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.data_preview.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.data_preview.setAlternatingRowColors(True)
        self.data_preview.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.data_preview.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.data_preview.setTextElideMode(QtCore.Qt.ElideRight)
        self.data_preview.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.data_preview.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.data_preview.setSortingEnabled(True)
        self.data_preview.setObjectName(_fromUtf8("data_preview"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setContentsMargins(4, -1, -1, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.group_aggregation = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_aggregation.sizePolicy().hasHeightForWidth())
        self.group_aggregation.setSizePolicy(sizePolicy)
        self.group_aggregation.setObjectName(_fromUtf8("group_aggregation"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.group_aggregation)
        self.verticalLayout_2.setContentsMargins(8, -1, 8, 6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radio_aggregate_none = QtGui.QRadioButton(self.group_aggregation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_aggregate_none.sizePolicy().hasHeightForWidth())
        self.radio_aggregate_none.setSizePolicy(sizePolicy)
        self.radio_aggregate_none.setChecked(True)
        self.radio_aggregate_none.setObjectName(_fromUtf8("radio_aggregate_none"))
        self.verticalLayout_2.addWidget(self.radio_aggregate_none)
        self.radio_aggregate_uniques = QtGui.QRadioButton(self.group_aggregation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_aggregate_uniques.sizePolicy().hasHeightForWidth())
        self.radio_aggregate_uniques.setSizePolicy(sizePolicy)
        self.radio_aggregate_uniques.setChecked(False)
        self.radio_aggregate_uniques.setObjectName(_fromUtf8("radio_aggregate_uniques"))
        self.verticalLayout_2.addWidget(self.radio_aggregate_uniques)
        self.radio_aggregate_frequencies = QtGui.QRadioButton(self.group_aggregation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_aggregate_frequencies.sizePolicy().hasHeightForWidth())
        self.radio_aggregate_frequencies.setSizePolicy(sizePolicy)
        self.radio_aggregate_frequencies.setObjectName(_fromUtf8("radio_aggregate_frequencies"))
        self.verticalLayout_2.addWidget(self.radio_aggregate_frequencies)
        self.radio_aggregate_contingency = QtGui.QRadioButton(self.group_aggregation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_aggregate_contingency.sizePolicy().hasHeightForWidth())
        self.radio_aggregate_contingency.setSizePolicy(sizePolicy)
        self.radio_aggregate_contingency.setObjectName(_fromUtf8("radio_aggregate_contingency"))
        self.verticalLayout_2.addWidget(self.radio_aggregate_contingency)
        self.radio_aggregate_collocations = QtGui.QRadioButton(self.group_aggregation)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_aggregate_collocations.sizePolicy().hasHeightForWidth())
        self.radio_aggregate_collocations.setSizePolicy(sizePolicy)
        self.radio_aggregate_collocations.setObjectName(_fromUtf8("radio_aggregate_collocations"))
        self.verticalLayout_2.addWidget(self.radio_aggregate_collocations)
        self.verticalLayout_4.addWidget(self.group_aggregation)
        spacerItem3 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.verticalLayout_6.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar()
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHilfe = QtGui.QMenu(self.menubar)
        self.menuHilfe.setObjectName(_fromUtf8("menuHilfe"))
        self.menuCorpus = QtGui.QMenu(self.menubar)
        self.menuCorpus.setObjectName(_fromUtf8("menuCorpus"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuAnalyse = QtGui.QMenu(self.menubar)
        self.menuAnalyse.setObjectName(_fromUtf8("menuAnalyse"))
        self.menuFrequencies = QtGui.QMenu(self.menuAnalyse)
        self.menuFrequencies.setObjectName(_fromUtf8("menuFrequencies"))
        self.menuFrequency_maps = QtGui.QMenu(self.menuAnalyse)
        self.menuFrequency_maps.setObjectName(_fromUtf8("menuFrequency_maps"))
        self.menuCorpus_locations = QtGui.QMenu(self.menuAnalyse)
        self.menuCorpus_locations.setObjectName(_fromUtf8("menuCorpus_locations"))
        self.menuDensity_plots = QtGui.QMenu(self.menuAnalyse)
        self.menuDensity_plots.setObjectName(_fromUtf8("menuDensity_plots"))
        self.menuTime_data = QtGui.QMenu(self.menuAnalyse)
        self.menuTime_data.setObjectName(_fromUtf8("menuTime_data"))
        self.menu_Results = QtGui.QMenu(self.menubar)
        self.menu_Results.setObjectName(_fromUtf8("menu_Results"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusbar.sizePolicy().hasHeightForWidth())
        self.statusbar.setSizePolicy(sizePolicy)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_open_input_file = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.action_open_input_file.setIcon(icon)
        self.action_open_input_file.setObjectName(_fromUtf8("action_open_input_file"))
        self.action_help = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("help-contents"))
        self.action_help.setIcon(icon)
        self.action_help.setObjectName(_fromUtf8("action_help"))
        self.action_about_coquery = QtGui.QAction(MainWindow)
        self.action_about_coquery.setObjectName(_fromUtf8("action_about_coquery"))
        self.actionDummy = QtGui.QAction(MainWindow)
        self.actionDummy.setObjectName(_fromUtf8("actionDummy"))
        self.action_distinct_tokens = QtGui.QAction(MainWindow)
        self.action_distinct_tokens.setObjectName(_fromUtf8("action_distinct_tokens"))
        self.action_frequency = QtGui.QAction(MainWindow)
        self.action_frequency.setObjectName(_fromUtf8("action_frequency"))
        self.action_all_tokens = QtGui.QAction(MainWindow)
        self.action_all_tokens.setObjectName(_fromUtf8("action_all_tokens"))
        self.action_statistics = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("view-statistics"))
        self.action_statistics.setIcon(icon)
        self.action_statistics.setObjectName(_fromUtf8("action_statistics"))
        self.action_connection_settings = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("server-database"))
        self.action_connection_settings.setIcon(icon)
        self.action_connection_settings.setObjectName(_fromUtf8("action_connection_settings"))
        self.action_settings = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("configure"))
        self.action_settings.setIcon(icon)
        self.action_settings.setObjectName(_fromUtf8("action_settings"))
        self.action_quit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("application-exit"))
        self.action_quit.setIcon(icon)
        self.action_quit.setObjectName(_fromUtf8("action_quit"))
        self.action_build_corpus = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-new"))
        self.action_build_corpus.setIcon(icon)
        self.action_build_corpus.setObjectName(_fromUtf8("action_build_corpus"))
        self.action_remove_corpus = QtGui.QAction(MainWindow)
        self.action_remove_corpus.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-delete"))
        self.action_remove_corpus.setIcon(icon)
        self.action_remove_corpus.setObjectName(_fromUtf8("action_remove_corpus"))
        self.action_manage_corpus = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("server-database"))
        self.action_manage_corpus.setIcon(icon)
        self.action_manage_corpus.setObjectName(_fromUtf8("action_manage_corpus"))
        self.action_tree_map = QtGui.QAction(MainWindow)
        self.action_tree_map.setEnabled(False)
        self.action_tree_map.setObjectName(_fromUtf8("action_tree_map"))
        self.action_heat_map = QtGui.QAction(MainWindow)
        self.action_heat_map.setEnabled(True)
        self.action_heat_map.setObjectName(_fromUtf8("action_heat_map"))
        self.action_word_cloud = QtGui.QAction(MainWindow)
        self.action_word_cloud.setEnabled(False)
        self.action_word_cloud.setObjectName(_fromUtf8("action_word_cloud"))
        self.action_barcode_plot = QtGui.QAction(MainWindow)
        self.action_barcode_plot.setObjectName(_fromUtf8("action_barcode_plot"))
        self.action_beeswarm_plot = QtGui.QAction(MainWindow)
        self.action_beeswarm_plot.setObjectName(_fromUtf8("action_beeswarm_plot"))
        self.action_barchart_plot = QtGui.QAction(MainWindow)
        self.action_barchart_plot.setObjectName(_fromUtf8("action_barchart_plot"))
        self.action_time_series_plot = QtGui.QAction(MainWindow)
        self.action_time_series_plot.setObjectName(_fromUtf8("action_time_series_plot"))
        self.action_corpus_documentation = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("help-browser"))
        self.action_corpus_documentation.setIcon(icon)
        self.action_corpus_documentation.setObjectName(_fromUtf8("action_corpus_documentation"))
        self.action_percentage_area_plot = QtGui.QAction(MainWindow)
        self.action_percentage_area_plot.setObjectName(_fromUtf8("action_percentage_area_plot"))
        self.action_stacked_area_plot = QtGui.QAction(MainWindow)
        self.action_stacked_area_plot.setObjectName(_fromUtf8("action_stacked_area_plot"))
        self.action_line_plot = QtGui.QAction(MainWindow)
        self.action_line_plot.setObjectName(_fromUtf8("action_line_plot"))
        self.actionStop_words = QtGui.QAction(MainWindow)
        self.actionStop_words.setObjectName(_fromUtf8("actionStop_words"))
        self.actionStop_words_2 = QtGui.QAction(MainWindow)
        self.actionStop_words_2.setObjectName(_fromUtf8("actionStop_words_2"))
        self.action_percentage_bars = QtGui.QAction(MainWindow)
        self.action_percentage_bars.setObjectName(_fromUtf8("action_percentage_bars"))
        self.action_stacked_bars = QtGui.QAction(MainWindow)
        self.action_stacked_bars.setObjectName(_fromUtf8("action_stacked_bars"))
        self.action_view_log = QtGui.QAction(MainWindow)
        self.action_view_log.setObjectName(_fromUtf8("action_view_log"))
        self.action_mysql_server_help = QtGui.QAction(MainWindow)
        self.action_mysql_server_help.setObjectName(_fromUtf8("action_mysql_server_help"))
        self.action_Column_context_menu = QtGui.QAction(MainWindow)
        self.action_Column_context_menu.setObjectName(_fromUtf8("action_Column_context_menu"))
        self.action_Row_context_menu = QtGui.QAction(MainWindow)
        self.action_Row_context_menu.setObjectName(_fromUtf8("action_Row_context_menu"))
        self.actionCopy_to_clipboard = QtGui.QAction(MainWindow)
        self.actionCopy_to_clipboard.setObjectName(_fromUtf8("actionCopy_to_clipboard"))
        self.actionSave_results = QtGui.QAction(MainWindow)
        self.actionSave_results.setObjectName(_fromUtf8("actionSave_results"))
        self.action_Selection_menu = QtGui.QAction(MainWindow)
        self.action_Selection_menu.setObjectName(_fromUtf8("action_Selection_menu"))
        self.action_bubble_chart = QtGui.QAction(MainWindow)
        self.action_bubble_chart.setObjectName(_fromUtf8("action_bubble_chart"))
        self.action_save_results = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.action_save_results.setIcon(icon)
        self.action_save_results.setObjectName(_fromUtf8("action_save_results"))
        self.action_copy_to_clipboard = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-copy"))
        self.action_copy_to_clipboard.setIcon(icon)
        self.action_copy_to_clipboard.setObjectName(_fromUtf8("action_copy_to_clipboard"))
        self.action_kde_plot = QtGui.QAction(MainWindow)
        self.action_kde_plot.setObjectName(_fromUtf8("action_kde_plot"))
        self.action_ecd_plot = QtGui.QAction(MainWindow)
        self.action_ecd_plot.setObjectName(_fromUtf8("action_ecd_plot"))
        self.action_save_selection = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.action_save_selection.setIcon(icon)
        self.action_save_selection.setObjectName(_fromUtf8("action_save_selection"))
        self.action_toggle_filters = QtGui.QAction(MainWindow)
        self.action_toggle_filters.setCheckable(True)
        self.action_toggle_filters.setObjectName(_fromUtf8("action_toggle_filters"))
        self.action_toggle_stopwords = QtGui.QAction(MainWindow)
        self.action_toggle_stopwords.setCheckable(True)
        self.action_toggle_stopwords.setObjectName(_fromUtf8("action_toggle_stopwords"))
        self.action_create_textgrid = QtGui.QAction(MainWindow)
        self.action_create_textgrid.setObjectName(_fromUtf8("action_create_textgrid"))
        self.menuFile.addAction(self.action_save_results)
        self.menuFile.addAction(self.action_save_selection)
        self.menuFile.addAction(self.action_create_textgrid)
        self.menuFile.addAction(self.action_copy_to_clipboard)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_view_log)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_quit)
        self.menuHilfe.addAction(self.action_help)
        self.menuHilfe.addSeparator()
        self.menuHilfe.addAction(self.action_about_coquery)
        self.menuCorpus.addAction(self.action_manage_corpus)
        self.menuCorpus.addSeparator()
        self.menuCorpus.addAction(self.action_statistics)
        self.menuCorpus.addAction(self.action_corpus_documentation)
        self.menuSettings.addAction(self.action_connection_settings)
        self.menuSettings.addAction(self.action_settings)
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.action_toggle_filters)
        self.menuSettings.addAction(self.action_toggle_stopwords)
        self.menuFrequencies.addAction(self.action_percentage_bars)
        self.menuFrequencies.addAction(self.action_stacked_bars)
        self.menuFrequencies.addAction(self.action_barchart_plot)
        self.menuFrequency_maps.addAction(self.action_heat_map)
        self.menuFrequency_maps.addAction(self.action_tree_map)
        self.menuFrequency_maps.addAction(self.action_word_cloud)
        self.menuFrequency_maps.addAction(self.action_bubble_chart)
        self.menuCorpus_locations.addAction(self.action_barcode_plot)
        self.menuCorpus_locations.addAction(self.action_beeswarm_plot)
        self.menuDensity_plots.addAction(self.action_kde_plot)
        self.menuDensity_plots.addAction(self.action_ecd_plot)
        self.menuTime_data.addAction(self.action_percentage_area_plot)
        self.menuTime_data.addAction(self.action_stacked_area_plot)
        self.menuTime_data.addAction(self.action_line_plot)
        self.menuAnalyse.addAction(self.menuCorpus_locations.menuAction())
        self.menuAnalyse.addAction(self.menuFrequencies.menuAction())
        self.menuAnalyse.addAction(self.menuTime_data.menuAction())
        self.menuAnalyse.addAction(self.menuFrequency_maps.menuAction())
        self.menuAnalyse.addAction(self.menuDensity_plots.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCorpus.menuAction())
        self.menubar.addAction(self.menu_Results.menuAction())
        self.menubar.addAction(self.menuAnalyse.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.button_filters, self.button_stopwords)
        MainWindow.setTabOrder(self.button_stopwords, self.button_run_query)
        MainWindow.setTabOrder(self.button_run_query, self.data_preview)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Coquery", None))
        self.box_corpus_select.setTitle(_translate("MainWindow", "Co&rpus", None))
        self.box_context_mode.setTitle(_translate("MainWindow", "Conte&xt", None))
        self.radio_context_none.setText(_translate("MainWindow", "None", None))
        self.radio_context_mode_kwic.setText(_translate("MainWindow", "KWIC", None))
        self.radio_context_mode_string.setText(_translate("MainWindow", "Single string", None))
        self.radio_context_mode_columns.setText(_translate("MainWindow", "Columns", None))
        self.context_left_span.setPrefix(_translate("MainWindow", "Left: ", None))
        self.context_right_span.setPrefix(_translate("MainWindow", "Right: ", None))
        self.button_filters.setText(_translate("MainWindow", "Fil&ters", None))
        self.button_stopwords.setText(_translate("MainWindow", "Stop &words", None))
        self.button_run_query.setText(_translate("MainWindow", "&Query", None))
        self.box_input_settings.setTitle(_translate("MainWindow", "Query &strings", None))
        self.button_browse_file.setText(_translate("MainWindow", "&Open", None))
        self.button_browse_file.setShortcut(_translate("MainWindow", "Alt+B", None))
        self.button_file_options.setText(_translate("MainWindow", "O&ptions", None))
        self.button_file_options.setShortcut(_translate("MainWindow", "Alt+B", None))
        self.edit_file_name.setPlaceholderText(_translate("MainWindow", "Choose an input file", None))
        self.box_output_options.setTitle(_translate("MainWindow", "O&utput columns", None))
        self.group_aggregation.setTitle(_translate("MainWindow", "&Aggregation", None))
        self.radio_aggregate_none.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Do not aggregate the query results.</span></p><p>Every token that matches the query string is listed in the \'Query results\' table. </p></body></html>", None))
        self.radio_aggregate_none.setText(_translate("MainWindow", "None", None))
        self.radio_aggregate_uniques.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Show only types.</span></p><p>The tokens matching the query string are aggregated so that duplicate matches are dropped. The \'Query results\' table shows only distinct types, and no duplicate tokens. </p></body></html>", None))
        self.radio_aggregate_uniques.setText(_translate("MainWindow", "Types", None))
        self.radio_aggregate_frequencies.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Show the frequency of each token.</span></p><p>\n"
"The number of occurrences of each token matching the query string is counted. The \'Query results\' table shows one row for each token, with the number of occurrences in the column \'Frequency\' . </p></body></html>", None))
        self.radio_aggregate_frequencies.setText(_translate("MainWindow", "Frequency", None))
        self.radio_aggregate_contingency.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Show a contingency table of the last query.</span></p><p>The number of occurrences of the tokens matching the query string are counted and arranged in a contingency table. </p></body></html>", None))
        self.radio_aggregate_contingency.setText(_translate("MainWindow", "Contingency", None))
        self.radio_aggregate_collocations.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Show collocations.</span></p><p>For the tokens matching the query string, the left and right context as defined by the user is also queried for collocate words. The \'Query results\' table shows one row for each collocate word, together with several collocation statistics. </p></body></html>", None))
        self.radio_aggregate_collocations.setText(_translate("MainWindow", "Collocations", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuHilfe.setTitle(_translate("MainWindow", "&Help", None))
        self.menuCorpus.setTitle(_translate("MainWindow", "&Corpus", None))
        self.menuSettings.setTitle(_translate("MainWindow", "&Preferences", None))
        self.menuAnalyse.setTitle(_translate("MainWindow", "&Visualizations", None))
        self.menuFrequencies.setTitle(_translate("MainWindow", "&Bar charts", None))
        self.menuFrequency_maps.setTitle(_translate("MainWindow", "Frequency maps", None))
        self.menuCorpus_locations.setTitle(_translate("MainWindow", "&Corpus locations", None))
        self.menuDensity_plots.setTitle(_translate("MainWindow", "Density plots", None))
        self.menuTime_data.setTitle(_translate("MainWindow", "&Time data", None))
        self.menu_Results.setTitle(_translate("MainWindow", "&Output", None))
        self.action_open_input_file.setText(_translate("MainWindow", "&Open input file...", None))
        self.action_open_input_file.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.action_help.setText(_translate("MainWindow", "&Help", None))
        self.action_help.setShortcut(_translate("MainWindow", "F1", None))
        self.action_about_coquery.setText(_translate("MainWindow", "&About Coquery", None))
        self.actionDummy.setText(_translate("MainWindow", "Dummy", None))
        self.action_distinct_tokens.setText(_translate("MainWindow", "Distinct tokens", None))
        self.action_frequency.setText(_translate("MainWindow", "Frequency", None))
        self.action_all_tokens.setText(_translate("MainWindow", "All tokens", None))
        self.action_statistics.setText(_translate("MainWindow", "Corpus &statistics", None))
        self.action_connection_settings.setText(_translate("MainWindow", "&Database connections...", None))
        self.action_settings.setText(_translate("MainWindow", "&Settings...", None))
        self.action_quit.setText(_translate("MainWindow", "&Quit", None))
        self.action_quit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.action_build_corpus.setText(_translate("MainWindow", "&Build new corpus...", None))
        self.action_build_corpus.setToolTip(_translate("MainWindow", "Build a new corpus from text files in a folder", None))
        self.action_remove_corpus.setText(_translate("MainWindow", "&Remove corpus...", None))
        self.action_remove_corpus.setToolTip(_translate("MainWindow", "Permanently and irrevocably remove corpus database", None))
        self.action_manage_corpus.setText(_translate("MainWindow", "Corpus &manager...", None))
        self.action_manage_corpus.setToolTip(_translate("MainWindow", "Install a corpus into a MySQL database", None))
        self.action_manage_corpus.setShortcut(_translate("MainWindow", "Ctrl+M", None))
        self.action_tree_map.setText(_translate("MainWindow", "&Tree map", None))
        self.action_heat_map.setText(_translate("MainWindow", "&Heat map", None))
        self.action_word_cloud.setText(_translate("MainWindow", "Word cloud", None))
        self.action_barcode_plot.setText(_translate("MainWindow", "&Barcode plot", None))
        self.action_beeswarm_plot.setText(_translate("MainWindow", "Bee&swarm plot", None))
        self.action_barchart_plot.setText(_translate("MainWindow", "&Bars", None))
        self.action_time_series_plot.setText(_translate("MainWindow", "T&ime series", None))
        self.action_corpus_documentation.setText(_translate("MainWindow", "Corpus &documentation...", None))
        self.action_percentage_area_plot.setText(_translate("MainWindow", "&Percentage areas", None))
        self.action_stacked_area_plot.setText(_translate("MainWindow", "&Stacked areas", None))
        self.action_line_plot.setText(_translate("MainWindow", "&Lines", None))
        self.actionStop_words.setText(_translate("MainWindow", "Stop words...", None))
        self.actionStop_words_2.setText(_translate("MainWindow", "&Stop words...", None))
        self.action_percentage_bars.setText(_translate("MainWindow", "&Percentage bars", None))
        self.action_stacked_bars.setText(_translate("MainWindow", "&Stacked bars", None))
        self.action_view_log.setText(_translate("MainWindow", "View &log file...", None))
        self.action_mysql_server_help.setText(_translate("MainWindow", "MySQL server help", None))
        self.action_Column_context_menu.setText(_translate("MainWindow", "[Column context menu]", None))
        self.action_Row_context_menu.setText(_translate("MainWindow", "[Row context menu]", None))
        self.actionCopy_to_clipboard.setText(_translate("MainWindow", "Copy to clipboard", None))
        self.actionSave_results.setText(_translate("MainWindow", "Save", None))
        self.action_Selection_menu.setText(_translate("MainWindow", "[Selection menu]", None))
        self.action_bubble_chart.setText(_translate("MainWindow", "&Bubble chart", None))
        self.action_save_results.setText(_translate("MainWindow", "&Save results...", None))
        self.action_save_results.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.action_copy_to_clipboard.setText(_translate("MainWindow", "&Copy selection to clipboard", None))
        self.action_copy_to_clipboard.setShortcut(_translate("MainWindow", "Ctrl+C", None))
        self.action_kde_plot.setText(_translate("MainWindow", "Kernel Density Estimate", None))
        self.action_ecd_plot.setText(_translate("MainWindow", "Estimated cumulative distribution", None))
        self.action_save_selection.setText(_translate("MainWindow", "Sa&ve selection...", None))
        self.action_save_selection.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.action_toggle_filters.setText(_translate("MainWindow", "Use &filters", None))
        self.action_toggle_stopwords.setText(_translate("MainWindow", "Use stop&words", None))
        self.action_create_textgrid.setText(_translate("MainWindow", "Create te&xtgrid...", None))
