sudo: false
language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO_VERSION="Django>=1.6,<1.7"
  - DJANGO_VERSION="Django>=1.7,<1.8"
  - DJANGO_VERSION="Django>=1.8,<1.9"
  - DJANGO_VERSION="Django>=1.9,<1.10"
  - DJANGO_VERSION="https://github.com/django/django/archive/master.tar.gz"
install:
  - pip install -q "$DJANGO_VERSION"
  - pip install pyaml
script: python -Wall tests/runtests.py
matrix:
  allow_failures:
    - env: DJANGO_VERSION="https://github.com/django/django/archive/master.tar.gz"
