
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "1f1b3fdd491462b526dfebff89ffb2f1cc5a4a27",
 "version": "1.0.0.post.dev177"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
