# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20160611_1255'),
        ('notifications', '0004_auto_20160611_1233'),
    ]

    operations = [
    ]
