__version__ = "0.5.1"
__git_commiter_name__ = "Itai Shirav"
__git_commiter_email__ = "itais@infinidat.com"
__git_branch__ = '(detached from v0.5.1)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '8a7560b9ef10bf35e5ccbe77b0bb07d8ab378c18'
__git_head_subject__ = 'Finished Release v0.5.1'
__git_head_message__ = ''
__git_dirty_diff__ = ''
__git_commit_date__ = '2016-06-28 11:11:41'
