plugins:
  xls:
    # mandatory properties for every plugin
    module:
      package: metzoo-python-parser-xls-consumo-puan-plugin
      import: from metzoo.plugins import xls_consumo_puan

    # specific properties for the plugin (this could be anything)
    path:         "//Paralelo_seguro/ReporteDiarioEnergia"
  
    mapping:
      "Secado 1":               {agent: "puan.energia", metric: "consumo.secado1"}
      "Secado 2":               {agent: "puan.energia", metric: "consumo.secado2"}
      "Secado 3":               {agent: "puan.energia", metric: "consumo.secado3"}
      "Secado 4":               {agent: "puan.energia", metric: "consumo.secado4"}
      "Refrigeración 1":        {agent: "puan.energia", metric: "consumo.refrigeracion1"}
      "Refrigeración 2":        {agent: "puan.energia", metric: "consumo.refrigeracion2"}
      "Refrigeración 3":        {agent: "puan.energia", metric: "consumo.refrigeracion3"}
      "Refrigeración 4":        {agent: "puan.energia", metric: "consumo.refrigeracion4"}
      "Grupo 1":                {agent: "puan.energia", metric: "consumo.grupo1"}
      "Grupo 2":                {agent: "puan.energia", metric: "consumo.grupo2"}
      "Grupo 3":                {agent: "puan.energia", metric: "consumo.grupo3"}
      "Grupo 4":                {agent: "puan.energia", metric: "consumo.grupo4"}
      "Grupo 5":                {agent: "puan.energia", metric: "consumo.grupo5"}
      "Germinación 1":          {agent: "puan.energia", metric: "consumo.germinacion1"}
      "Germinación 2":          {agent: "puan.energia", metric: "consumo.germinacion2"}
      "Germinación 3":          {agent: "puan.energia", metric: "consumo.germinacion3"}
      "Germinación 4":          {agent: "puan.energia", metric: "consumo.germinacion4"}
      "Germinación 5":          {agent: "puan.energia", metric: "consumo.germinacion5"}
      "Germinación 6":          {agent: "puan.energia", metric: "consumo.germinacion6"}
      "Auxiliar":               {agent: "puan.energia", metric: "consumo.auxiliar"}
      "Administración":         {agent: "puan.energia", metric: "consumo.administracion"}
      "Lavado":                 {agent: "puan.energia", metric: "consumo.lavado"}
      "Sala de Bombas":         {agent: "puan.energia", metric: "consumo.sala_de_bombas"}
      "Taller Eléctrico":       {agent: "puan.energia", metric: "consumo.taller_electrico"}
      "Celda de media tensión": {agent: "puan.energia", metric: "consumo.celda_de_media_tension"}
      "Iluminación y tomas":    {agent: "puan.energia", metric: "consumo.iluminacion_y_tomas"}
      "Planta de Efluentes":    {agent: "puan.energia", metric: "consumo.planta_de_efluentes"}
      "Peletizadora":           {agent: "puan.energia", metric: "consumo.peletizadora"}
      "Torre de Norias":        {agent: "puan.energia", metric: "consumo.torre_de_norias"}
      "Enfriamiento":           {agent: "puan.energia", metric: "consumo.enfriamiento"}
      "Quemador 1":             {agent: "puan.energia", metric: "caudal.quemador1"}
      "Quemador 2":             {agent: "puan.energia", metric: "caudal.quemador2"}
      "Quemador 3":             {agent: "puan.energia", metric: "caudal.quemador3"}
      "Quemador 4":             {agent: "puan.energia", metric: "caudal.quemador4"}
      "Quemador 5":             {agent: "puan.energia", metric: "caudal.quemador5"}
      "Quemador 6":             {agent: "puan.energia", metric: "caudal.quemador6"}
