
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '2.1.0'
version_full = '195ad64c625c168023329c626daa7c367600486d'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

