# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/colin/Documents/hackedit-cobol/data/forms/settings_page_compiler.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(794, 800)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.combo_configs = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_configs.sizePolicy().hasHeightForWidth())
        self.combo_configs.setSizePolicy(sizePolicy)
        self.combo_configs.setObjectName("combo_configs")
        self.horizontalLayout_4.addWidget(self.combo_configs)
        self.bt_add_cfg = QtWidgets.QToolButton(self.groupBox)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.bt_add_cfg.setIcon(icon)
        self.bt_add_cfg.setObjectName("bt_add_cfg")
        self.horizontalLayout_4.addWidget(self.bt_add_cfg)
        self.bt_copy_cfg = QtWidgets.QToolButton(self.groupBox)
        icon = QtGui.QIcon.fromTheme("edit-copy")
        self.bt_copy_cfg.setIcon(icon)
        self.bt_copy_cfg.setObjectName("bt_copy_cfg")
        self.horizontalLayout_4.addWidget(self.bt_copy_cfg)
        self.bt_rm_cfg = QtWidgets.QToolButton(self.groupBox)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.bt_rm_cfg.setIcon(icon)
        self.bt_rm_cfg.setObjectName("bt_rm_cfg")
        self.horizontalLayout_4.addWidget(self.bt_rm_cfg)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.bt_rename_cfg = QtWidgets.QToolButton(self.groupBox)
        icon = QtGui.QIcon.fromTheme("edit-rename")
        self.bt_rename_cfg.setIcon(icon)
        self.bt_rename_cfg.setObjectName("bt_rename_cfg")
        self.horizontalLayout_4.addWidget(self.bt_rename_cfg)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_read_only = QtWidgets.QLabel(self.groupBox_2)
        self.label_read_only.setStyleSheet("background-color: #DD8080;\n"
"color: white;\n"
"padding: 10px;\n"
"border-radius:3px;")
        self.label_read_only.setObjectName("label_read_only")
        self.verticalLayout_2.addWidget(self.label_read_only)
        self.bt_check_compiler = QtWidgets.QToolButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_check_compiler.sizePolicy().hasHeightForWidth())
        self.bt_check_compiler.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("checkbox")
        self.bt_check_compiler.setIcon(icon)
        self.bt_check_compiler.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.bt_check_compiler.setObjectName("bt_check_compiler")
        self.verticalLayout_2.addWidget(self.bt_check_compiler)
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidget.setToolTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_setup = QtWidgets.QWidget()
        self.tab_setup.setObjectName("tab_setup")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_setup)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_setup)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 732, 530))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.edit_compiler_path = PathLineEdit(self.scrollAreaWidgetContents)
        self.edit_compiler_path.setObjectName("edit_compiler_path")
        self.horizontalLayout_2.addWidget(self.edit_compiler_path)
        self.bt_choose_compiler_path = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.bt_choose_compiler_path.setIcon(icon)
        self.bt_choose_compiler_path.setObjectName("bt_choose_compiler_path")
        self.horizontalLayout_2.addWidget(self.bt_choose_compiler_path)
        self.bt_compiler_info = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        icon = QtGui.QIcon.fromTheme("dialog-information")
        self.bt_compiler_info.setIcon(icon)
        self.bt_compiler_info.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.bt_compiler_info.setObjectName("bt_compiler_info")
        self.horizontalLayout_2.addWidget(self.bt_compiler_info)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.edit_cobcrun_path = PathLineEdit(self.scrollAreaWidgetContents)
        self.edit_cobcrun_path.setObjectName("edit_cobcrun_path")
        self.horizontalLayout_5.addWidget(self.edit_cobcrun_path)
        self.bt_choose_cobcrun_path = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.bt_choose_cobcrun_path.setIcon(icon)
        self.bt_choose_cobcrun_path.setObjectName("bt_choose_cobcrun_path")
        self.horizontalLayout_5.addWidget(self.bt_choose_cobcrun_path)
        self.bt_runner_info = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        icon = QtGui.QIcon.fromTheme("dialog-information")
        self.bt_runner_info.setIcon(icon)
        self.bt_runner_info.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.bt_runner_info.setObjectName("bt_runner_info")
        self.horizontalLayout_5.addWidget(self.bt_runner_info)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.edit_vcvars = PathLineEdit(self.scrollAreaWidgetContents)
        self.edit_vcvars.setObjectName("edit_vcvars")
        self.horizontalLayout_8.addWidget(self.edit_vcvars)
        self.bt_vcvars = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.bt_vcvars.setIcon(icon)
        self.bt_vcvars.setObjectName("bt_vcvars")
        self.horizontalLayout_8.addWidget(self.bt_vcvars)
        self.combo_arch = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.combo_arch.setEditable(False)
        self.combo_arch.setObjectName("combo_arch")
        self.combo_arch.addItem("")
        self.combo_arch.addItem("")
        self.horizontalLayout_8.addWidget(self.combo_arch)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.lbl_vcvars = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.lbl_vcvars.setObjectName("lbl_vcvars")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_vcvars)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table_env_vars = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.table_env_vars.setMinimumSize(QtCore.QSize(0, 334))
        self.table_env_vars.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_env_vars.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_env_vars.setObjectName("table_env_vars")
        self.table_env_vars.setColumnCount(2)
        self.table_env_vars.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.table_env_vars.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_env_vars.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_env_vars.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_env_vars.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_env_vars.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_env_vars.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_env_vars.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_env_vars.setItem(2, 0, item)
        self.table_env_vars.horizontalHeader().setDefaultSectionSize(150)
        self.table_env_vars.horizontalHeader().setStretchLastSection(True)
        self.table_env_vars.verticalHeader().setVisible(False)
        self.table_env_vars.verticalHeader().setCascadingSectionResizes(False)
        self.horizontalLayout.addWidget(self.table_env_vars)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bt_add_env_var = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.bt_add_env_var.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.bt_add_env_var.setIcon(icon)
        self.bt_add_env_var.setObjectName("bt_add_env_var")
        self.verticalLayout_3.addWidget(self.bt_add_env_var)
        self.bt_rm_env_var = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.bt_rm_env_var.setText("")
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.bt_rm_env_var.setIcon(icon)
        self.bt_rm_env_var.setObjectName("bt_rm_env_var")
        self.verticalLayout_3.addWidget(self.bt_rm_env_var)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.edit_exe_ext = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edit_exe_ext.setObjectName("edit_exe_ext")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edit_exe_ext)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.edit_module_ext = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edit_module_ext.setObjectName("edit_module_ext")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.edit_module_ext)
        self.label_2.raise_()
        self.label.raise_()
        self.lbl_vcvars.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.edit_exe_ext.raise_()
        self.label_6.raise_()
        self.edit_module_ext.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_setup, "")
        self.tab_options = QtWidgets.QWidget()
        self.tab_options.setToolTip("")
        self.tab_options.setObjectName("tab_options")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tab_options)
        self.formLayout_2.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setVerticalSpacing(9)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_36 = QtWidgets.QLabel(self.tab_options)
        self.label_36.setObjectName("label_36")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.edit_output_dir = PathLineEdit(self.tab_options)
        self.edit_output_dir.setText("")
        self.edit_output_dir.setObjectName("edit_output_dir")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.edit_output_dir)
        self.label_15 = QtWidgets.QLabel(self.tab_options)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(0, 0, -1, -1)
        self.gridLayout_5.setHorizontalSpacing(9)
        self.gridLayout_5.setVerticalSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cb_ftrace = QtWidgets.QCheckBox(self.tab_options)
        self.cb_ftrace.setObjectName("cb_ftrace")
        self.gridLayout_5.addWidget(self.cb_ftrace, 2, 0, 1, 1)
        self.cb_static = QtWidgets.QCheckBox(self.tab_options)
        self.cb_static.setObjectName("cb_static")
        self.gridLayout_5.addWidget(self.cb_static, 0, 0, 1, 1)
        self.cb_debugging_line = QtWidgets.QCheckBox(self.tab_options)
        self.cb_debugging_line.setObjectName("cb_debugging_line")
        self.gridLayout_5.addWidget(self.cb_debugging_line, 2, 2, 1, 1)
        self.cb_ftraceall = QtWidgets.QCheckBox(self.tab_options)
        self.cb_ftraceall.setObjectName("cb_ftraceall")
        self.gridLayout_5.addWidget(self.cb_ftraceall, 2, 1, 1, 1)
        self.cb_debug = QtWidgets.QCheckBox(self.tab_options)
        self.cb_debug.setToolTip("")
        self.cb_debug.setObjectName("cb_debug")
        self.gridLayout_5.addWidget(self.cb_debug, 0, 1, 1, 1)
        self.cb_g = QtWidgets.QCheckBox(self.tab_options)
        self.cb_g.setObjectName("cb_g")
        self.gridLayout_5.addWidget(self.cb_g, 0, 2, 1, 1)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.gridLayout_5)
        self.label_35 = QtWidgets.QLabel(self.tab_options)
        self.label_35.setObjectName("label_35")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.edit_extra_flags = QtWidgets.QLineEdit(self.tab_options)
        self.edit_extra_flags.setObjectName("edit_extra_flags")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.edit_extra_flags)
        self.label_37 = QtWidgets.QLabel(self.tab_options)
        self.label_37.setObjectName("label_37")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_12.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.list_copy_paths = QtWidgets.QListWidget(self.tab_options)
        self.list_copy_paths.setObjectName("list_copy_paths")
        self.horizontalLayout_12.addWidget(self.list_copy_paths)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.bt_abs_copy_path = QtWidgets.QToolButton(self.tab_options)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.bt_abs_copy_path.setIcon(icon)
        self.bt_abs_copy_path.setObjectName("bt_abs_copy_path")
        self.verticalLayout_12.addWidget(self.bt_abs_copy_path)
        self.bt_rel_copy_path = QtWidgets.QToolButton(self.tab_options)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.bt_rel_copy_path.setIcon(icon)
        self.bt_rel_copy_path.setObjectName("bt_rel_copy_path")
        self.verticalLayout_12.addWidget(self.bt_rel_copy_path)
        self.bt_rm_copy_path = QtWidgets.QToolButton(self.tab_options)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.bt_rm_copy_path.setIcon(icon)
        self.bt_rm_copy_path.setObjectName("bt_rm_copy_path")
        self.verticalLayout_12.addWidget(self.bt_rm_copy_path)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem1)
        self.horizontalLayout_12.addLayout(self.verticalLayout_12)
        self.horizontalLayout_12.setStretch(0, 1)
        self.formLayout_2.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_12)
        self.label_17 = QtWidgets.QLabel(self.tab_options)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.tab_options)
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_10.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.list_lib_paths = QtWidgets.QListWidget(self.tab_options)
        self.list_lib_paths.setObjectName("list_lib_paths")
        self.horizontalLayout_10.addWidget(self.list_lib_paths)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bt_abs_lib_path = QtWidgets.QToolButton(self.tab_options)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.bt_abs_lib_path.setIcon(icon)
        self.bt_abs_lib_path.setObjectName("bt_abs_lib_path")
        self.verticalLayout_4.addWidget(self.bt_abs_lib_path)
        self.bt_rel_lib_path = QtWidgets.QToolButton(self.tab_options)
        icon = QtGui.QIcon.fromTheme("list-add")
        self.bt_rel_lib_path.setIcon(icon)
        self.bt_rel_lib_path.setObjectName("bt_rel_lib_path")
        self.verticalLayout_4.addWidget(self.bt_rel_lib_path)
        self.bt_delete_lib_path = QtWidgets.QToolButton(self.tab_options)
        icon = QtGui.QIcon.fromTheme("list-remove")
        self.bt_delete_lib_path.setIcon(icon)
        self.bt_delete_lib_path.setObjectName("bt_delete_lib_path")
        self.verticalLayout_4.addWidget(self.bt_delete_lib_path)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.formLayout_2.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_10)
        self.edit_libs = QtWidgets.QLineEdit(self.tab_options)
        self.edit_libs.setObjectName("edit_libs")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.edit_libs)
        self.label_3 = QtWidgets.QLabel(self.tab_options)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.combo_standard = QtWidgets.QComboBox(self.tab_options)
        self.combo_standard.setObjectName("combo_standard")
        self.combo_standard.addItem("")
        self.combo_standard.addItem("")
        self.combo_standard.addItem("")
        self.combo_standard.addItem("")
        self.combo_standard.addItem("")
        self.combo_standard.addItem("")
        self.combo_standard.addItem("")
        self.combo_standard.addItem("")
        self.combo_standard.addItem("")
        self.combo_standard.addItem("")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.combo_standard)
        self.tabWidget.addTab(self.tab_options, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.lbl_cobc_version = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_cobc_version.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_cobc_version.setObjectName("lbl_cobc_version")
        self.verticalLayout_2.addWidget(self.lbl_cobc_version)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.edit_extensions = QtWidgets.QLineEdit(self.groupBox_3)
        self.edit_extensions.setObjectName("edit_extensions")
        self.gridLayout_2.addWidget(self.edit_extensions, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.combo_configs, self.bt_add_cfg)
        Form.setTabOrder(self.bt_add_cfg, self.bt_copy_cfg)
        Form.setTabOrder(self.bt_copy_cfg, self.bt_rm_cfg)
        Form.setTabOrder(self.bt_rm_cfg, self.bt_rename_cfg)
        Form.setTabOrder(self.bt_rename_cfg, self.edit_compiler_path)
        Form.setTabOrder(self.edit_compiler_path, self.bt_choose_compiler_path)
        Form.setTabOrder(self.bt_choose_compiler_path, self.edit_cobcrun_path)
        Form.setTabOrder(self.edit_cobcrun_path, self.bt_choose_cobcrun_path)
        Form.setTabOrder(self.bt_choose_cobcrun_path, self.edit_vcvars)
        Form.setTabOrder(self.edit_vcvars, self.bt_vcvars)
        Form.setTabOrder(self.bt_vcvars, self.edit_output_dir)
        Form.setTabOrder(self.edit_output_dir, self.cb_static)
        Form.setTabOrder(self.cb_static, self.cb_debug)
        Form.setTabOrder(self.cb_debug, self.cb_g)
        Form.setTabOrder(self.cb_g, self.cb_ftrace)
        Form.setTabOrder(self.cb_ftrace, self.cb_ftraceall)
        Form.setTabOrder(self.cb_ftraceall, self.cb_debugging_line)
        Form.setTabOrder(self.cb_debugging_line, self.edit_extra_flags)
        Form.setTabOrder(self.edit_extra_flags, self.list_copy_paths)
        Form.setTabOrder(self.list_copy_paths, self.bt_abs_copy_path)
        Form.setTabOrder(self.bt_abs_copy_path, self.bt_rel_copy_path)
        Form.setTabOrder(self.bt_rel_copy_path, self.bt_rm_copy_path)
        Form.setTabOrder(self.bt_rm_copy_path, self.list_lib_paths)
        Form.setTabOrder(self.list_lib_paths, self.bt_abs_lib_path)
        Form.setTabOrder(self.bt_abs_lib_path, self.bt_rel_lib_path)
        Form.setTabOrder(self.bt_rel_lib_path, self.bt_delete_lib_path)

    def retranslateUi(self, Form):
        from hackedit.api.gettext import get_translation
        _ = get_translation(package="hackedit-cobol")
        Form.setWindowTitle(_("Form"))
        self.groupBox.setTitle(_("Compilers"))
        self.combo_configs.setToolTip(_("The list of COBOL compiler configurations. \n"
"\n"
"The selected entry will be used as the default compiler when creating/opening a new project."))
        self.bt_add_cfg.setToolTip(_("Add new compiler configuration."))
        self.bt_add_cfg.setText(_("..."))
        self.bt_copy_cfg.setToolTip(_("Clone compiler configuration."))
        self.bt_copy_cfg.setText(_("..."))
        self.bt_rm_cfg.setToolTip(_("Remove compiler configuration."))
        self.bt_rm_cfg.setText(_("..."))
        self.bt_rename_cfg.setToolTip(_("Rename compiler configuration."))
        self.bt_rename_cfg.setText(_("..."))
        self.groupBox_2.setTitle(_("Configuration"))
        self.label_read_only.setText(_("<html><head/><body><p align=\"center\">This configuration is read-only. You must clone it if you want to modify it...</p></body></html>"))
        self.bt_check_compiler.setToolTip(_("Check if compiler works"))
        self.bt_check_compiler.setText(_("Check compiler configuration"))
        self.tab_setup.setToolTip(_("Cobol compiler setup.\n"
"\n"
"Configure oaths and environment variables and check if the compiler configuration works!"))
        self.label_2.setText(_("Compiler (cobc):"))
        self.edit_compiler_path.setToolTip(_("Full path to the compiler executable"))
        self.bt_choose_compiler_path.setToolTip(_("Choose compiler executable"))
        self.bt_choose_compiler_path.setText(_("..."))
        self.bt_compiler_info.setToolTip(_("<html><head/><body><p>Get more information about the compiler (by running cobc --info)</p><p><span style=\" font-style:italic;\">Note that only the latest builds of GnuCOBOL 2.0 have this option</span></p></body></html>"))
        self.bt_compiler_info.setText(_("More info"))
        self.label.setText(_("Module runner (cobcrun):"))
        self.edit_cobcrun_path.setToolTip(_("Full path to the module runner (cobcrun) executable"))
        self.bt_choose_cobcrun_path.setToolTip(_("Choose compiler executable"))
        self.bt_choose_cobcrun_path.setText(_("..."))
        self.bt_runner_info.setText(_("More info"))
        self.edit_vcvars.setToolTip(_("<html><head/><body><p>Path to VCVARSALL.bat. It is needed if you\'re using a GnuCobol compiler built with Visual Studio.</p><p><br/>The VCVARSALL.bat file is located under the VC directory of you Visual Studio installation. Make sure to use the same version as the one used to build the compiler!</p></body></html>"))
        self.bt_vcvars.setToolTip(_("Select vcvarsall.bat"))
        self.bt_vcvars.setText(_("..."))
        self.combo_arch.setToolTip(_("Architecture to set when querying vcvarsall"))
        self.combo_arch.setItemText(0, _("x86"))
        self.combo_arch.setItemText(1, _("x64"))
        self.lbl_vcvars.setText(_("vcvarsall.bat:"))
        self.label_5.setText(_("Environment variables:"))
        self.table_env_vars.setToolTip(_("<html><head/><body><p>The list of environment variables to set before compiling a file.</p><p>Note that the values defined in this list erase any previous value you might have defined in your system (empty values are not set).</p><p><br/></p></body></html>"))
        item = self.table_env_vars.horizontalHeaderItem(0)
        item.setText(_("Key"))
        item = self.table_env_vars.horizontalHeaderItem(1)
        item.setText(_("Value"))
        __sortingEnabled = self.table_env_vars.isSortingEnabled()
        self.table_env_vars.setSortingEnabled(False)
        item = self.table_env_vars.item(0, 0)
        item.setText(_("COB_CONFIG_DIR"))
        item = self.table_env_vars.item(1, 0)
        item.setText(_("COB_COPY_DIR"))
        item = self.table_env_vars.item(2, 0)
        item.setText(_("COB_LIB_PATH"))
        self.table_env_vars.setSortingEnabled(__sortingEnabled)
        self.bt_add_env_var.setToolTip(_("Add an environment variable to set on the compiler process."))
        self.bt_rm_env_var.setToolTip(_("Remove the selected environment variable."))
        self.label_4.setText(_("Executable extension:"))
        self.edit_exe_ext.setToolTip(_("The file extension to use for executables (.exe on Windows, empty everywhere else)."))
        self.label_6.setText(_("Module extension:"))
        self.edit_module_ext.setToolTip(_("The file extension used for modules: .dll on Windows, .so on GNU/Linux and .dylib on OSX."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_setup), _("Setup"))
        self.label_36.setText(_("Output directory:"))
        self.edit_output_dir.setToolTip(_("Choose where the binaries must be created. Relative paths are supported!"))
        self.label_15.setText(_("Compiler flags:"))
        self.cb_ftrace.setToolTip(_("<html><head/><body><p>Generate trace code</p><p>   - Executed SECTION/PARAGRAPH</p></body></html>"))
        self.cb_ftrace.setText(_("-ftrace"))
        self.cb_static.setToolTip(_("Link statically"))
        self.cb_static.setText(_("-static"))
        self.cb_debugging_line.setToolTip(_("<html><head/><body><p>Enable debugging lines</p><p>  - \'D\' in indicator column or floating &gt;&gt;D</p></body></html>"))
        self.cb_debugging_line.setText(_("-fdebugging-line"))
        self.cb_ftraceall.setToolTip(_("<html><head/><body><p>Generate trace code</p><p>  - Executed SECTION/PARAGRAPH/STATEMENTS</p><p>  - Turned on by -debug</p></body></html>"))
        self.cb_ftraceall.setText(_("-ftraceall"))
        self.cb_debug.setText(_("-debug"))
        self.cb_g.setToolTip(_("Enable C compiler debug / stack check / trace"))
        self.cb_g.setText(_("-g"))
        self.label_35.setText(_("Extra compiler flags:"))
        self.edit_extra_flags.setToolTip(_("<html><head/><body><p>List of extra compiler flags. Each entry in the list must be separated by a white space.</p></body></html>"))
        self.label_37.setText(_("Copybook paths:"))
        self.list_copy_paths.setToolTip(_("The list of copybook paths."))
        self.bt_abs_copy_path.setToolTip(_("Add an absolute copybook path"))
        self.bt_abs_copy_path.setText(_("..."))
        self.bt_rel_copy_path.setToolTip(_("Add a relative copybook path"))
        self.bt_rel_copy_path.setText(_("..."))
        self.bt_rm_copy_path.setToolTip(_("Delete selected path"))
        self.bt_rm_copy_path.setText(_("..."))
        self.label_17.setText(_("Library paths:"))
        self.label_18.setText(_("Libraries:"))
        self.list_lib_paths.setToolTip(_("<html><head/><body><p>The list of library paths.</p></body></html>"))
        self.bt_abs_lib_path.setToolTip(_("Add an absolute library path"))
        self.bt_abs_lib_path.setText(_("..."))
        self.bt_rel_lib_path.setToolTip(_("Add a relative library path"))
        self.bt_rel_lib_path.setText(_("..."))
        self.bt_delete_lib_path.setToolTip(_("Delete selected path"))
        self.bt_delete_lib_path.setText(_("..."))
        self.edit_libs.setToolTip(_("<html><head/><body><p>The list of libraries you would like your programs to link with (-l option).</p><p>Each entry in the list must be separated by a white space</p></body></html>"))
        self.label_3.setText(_("Standard:"))
        self.combo_standard.setItemText(0, _("default"))
        self.combo_standard.setItemText(1, _("cobol2002"))
        self.combo_standard.setItemText(2, _("cobol85"))
        self.combo_standard.setItemText(3, _("ibm"))
        self.combo_standard.setItemText(4, _("mvs"))
        self.combo_standard.setItemText(5, _("bs2000"))
        self.combo_standard.setItemText(6, _("mf"))
        self.combo_standard.setItemText(7, _("acu"))
        self.combo_standard.setItemText(8, _("cobol2014"))
        self.combo_standard.setItemText(9, _("none"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_options), _("Options"))
        self.lbl_cobc_version.setText(_("cobc version"))
        self.groupBox_3.setTitle(_("Compilable extensions"))
        self.edit_extensions.setToolTip(_("The list of file extensions that can be compiled."))

from hackedit.api.widgets import PathLineEdit
from . import hackedit_cobol_rc
