
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: PythonLibrary(BuildFileAddress(BuildFile(src/python/playpants/BUILD, FileSystemProjectTree(/volumes/mint2015-storage/Development/play-pants)), playpants))

from setuptools import setup

setup(**
{   'author': 'Nadav Sr. Samet',
    'author_email': 'nadav@thesamet.com',
    'classifiers': [   'Intended Audience :: Developers',
                       'License :: OSI Approved :: Apache Software License',
                       'Operating System :: OS Independent',
                       'Programming Language :: Python'],
    'description': 'Play plugin for Pants',
    'install_requires': [],
    'license': 'Apache License, Version 2.0',
    'name': 'thesamet.playpants',
    'package_data': {   },
    'package_dir': {   '': 'src'},
    'packages': ['playpants', 'playpants.targets', 'playpants.tasks'],
    'url': 'https://github.com/thesamet/playpants',
    'version': '0.1',
    'zip_safe': True}
)
