
# This file was generated by 'versioneer.py' (0.13+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.6'
version_full = '0c0d588d8cf7b1a645dbe359e1977c0984fa82eb'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

