#-*- coding:utf-8 -*-

# This file is generated from the AUTHORS file during the installation process.
# Do not edit it as your changes will be overwritten.

__authors__ = [
    u"Naveen Michaud-Agrawal",
    u"Elizabeth J. Denning",
    u"Christian Beckstein (logo)",
    u"Joshua L. Adelman",
    u"Balasubramanian",
    u"Jonathan Barnoud",
    u"Alejandro Bernardin",
    u"Bart Bruininks",
    u"Sébastien Buchoux",
    u"David Caplan",
    u"Matthieu Chavent",
    u"John Detlefs",
    u"Xavier Deupi",
    u"Jan Domanski",
    u"David L. Dotson",
    u"Lennard van der Feltz",
    u"Philip Fowler",
    u"Joseph Goose",
    u"Richard J. Gowers",
    u"Lukas Grossar",
    u"Abhinav Gupta",
    u"Benjamin Hall",
    u"Kyle J. Huston",
    u"Joe Jordan",
    u"Max Linke",
    u"Jinju Lu",
    u"Robert McGibbon",
    u"Manuel Nuno Melo",
    u"Alex Nesterenko",
    u"Hai Nguyen",
    u"Mattia F. Palermo",
    u"Danny Parton",
    u"Joshua L. Phillips",
    u"Tyler Reddy",
    u"Paul Rigor",
    u"Carlos Yanez S.",
    u"Utkarsh Saxena",
    u"Sean L. Seyler",
    u"Andy Somogyi",
    u"Caio S. Souza",
    u"Lukas Stelzl",
    u"Gorman Stock",
    u"Isaac Virshup",
    u"Zhuyi Xue",
    u"Oliver Beckstein"
]
