[package]

name = "fst-wrapper"
version = "0.0.1"
authors = ["Johannes Baiter <johannes.baiter@gmail.com>"]

[lib]
name = "fstwrapper"
crate-type = ["dylib"]

[dependencies]
libc = "0.2"
fst = "^0.1.30"
