# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 20:09
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='zipcode',
            field=localflavor.us.models.USZipCodeField(default='00000', max_length=10),
            preserve_default=False,
        ),
    ]
