# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_municipality_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='pickup_day',
        ),
        migrations.AlterField(
            model_name='district',
            name='pickup_time',
            field=models.CharField(default='every monday', max_length=255, verbose_name='Pick up time'),
            preserve_default=False,
        ),
    ]
