# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WechatBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WechatUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=255, unique=True)),
                ('nickname', models.CharField(max_length=255, null=True)),
                ('sex', models.CharField(max_length=1, null=True)),
                ('province', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('headimgurl', models.CharField(max_length=255, null=True)),
                ('privilege', models.CharField(max_length=1024, null=True)),
                ('unionid', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wechatbase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_wechat_web.WechatBase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
