__version__ = "0.2.7"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = 'develop'
__git_remote_tracking_branch__ = 'origin/develop'
__git_remote_url__ = 'git@git.infinidat.com:host-opensource/infi.docopt_completion.git'
__git_head_hash__ = 'adde45ddfbab8789a1ea44f26f71659c6517fab3'
__git_head_subject__ = 'Finished Release v0.2.7'
__git_head_message__ = ''
__git_dirty_diff__ = ''
__git_commit_date__ = '2016-06-22 15:37:19'
