
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.6.4'
version_full = 'ba07d6af8e63949a15a9a36a58fa6475e7fd4c76'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

