__version__ = "0.1.9"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(HEAD detached at v0.1.9)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'c3f6ba0f4908fc3e7c4e7b268e0aca6aaaf5d7f6'
__git_head_subject__ = 'Finished Release v0.1.9'
__git_head_message__ = ''
__git_dirty_diff__ = ''
__git_commit_date__ = '2016-06-22 15:46:57'
