# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/colin/dev/HackEdit/hackedit-python/data/forms/settings_page_interpreters.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(864, 548)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.bt_manage_interpreters = QtWidgets.QToolButton(self.groupBox)
        icon = QtGui.QIcon.fromTheme("preferences-system")
        self.bt_manage_interpreters.setIcon(icon)
        self.bt_manage_interpreters.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.bt_manage_interpreters.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.bt_manage_interpreters.setAutoRaise(False)
        self.bt_manage_interpreters.setObjectName("bt_manage_interpreters")
        self.horizontalLayout.addWidget(self.bt_manage_interpreters)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, -1, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.progress_bar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progress_bar.setMaximum(0)
        self.progress_bar.setProperty("value", -1)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout_3.addWidget(self.progress_bar)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bt_add_packages = QtWidgets.QToolButton(self.groupBox_2)
        self.bt_add_packages.setText("")
        icon = QtGui.QIcon.fromTheme("list-add")
        self.bt_add_packages.setIcon(icon)
        self.bt_add_packages.setObjectName("bt_add_packages")
        self.verticalLayout_2.addWidget(self.bt_add_packages)
        self.bt_rm_package = QtWidgets.QToolButton(self.groupBox_2)
        self.bt_rm_package.setText("")
        icon = QtGui.QIcon.fromTheme("edit-delete")
        self.bt_rm_package.setIcon(icon)
        self.bt_rm_package.setObjectName("bt_rm_package")
        self.verticalLayout_2.addWidget(self.bt_rm_package)
        self.bt_update_package = QtWidgets.QToolButton(self.groupBox_2)
        self.bt_update_package.setText("")
        icon = QtGui.QIcon.fromTheme("go-up")
        self.bt_update_package.setIcon(icon)
        self.bt_update_package.setObjectName("bt_update_package")
        self.verticalLayout_2.addWidget(self.bt_update_package)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        from hackedit.api.gettext import get_translation
        _ = get_translation(package="hackedit-python")
        Form.setWindowTitle(_("Form"))
        self.groupBox.setTitle(_("Default interpreter"))
        self.comboBox.setToolTip(_("Select the default interpreter that will be used when opening new projects."))
        self.bt_manage_interpreters.setToolTip(_("Manage python interpreters"))
        self.bt_manage_interpreters.setText(_("Manage  "))
        self.groupBox_2.setTitle(_("Packages"))
        self.tableWidget.setToolTip(_("The list of installed package for the selected interpreter."))
        self.tableWidget.setSortingEnabled(True)
        self.bt_add_packages.setToolTip(_("Install one or more packages"))
        self.bt_rm_package.setToolTip(_("Uninstall selected package"))
        self.bt_update_package.setToolTip(_("Update selected package"))

