package:
  name: brian2tools

requirements:
  build:
    - python
    - setuptools >=6.0
    - setuptools_scm
  run:
    - python
    - brian2 >=1.9
    - matplotlib >=1.3.1

test:
  # Python imports
  imports:
    - brian2tools
    - brian2tools.plotting

  commands:
    - MPLBACKEND=Agg py.test --pyargs brian2tools

  requires:
    - pytest

source:
  path: ../..

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

about:
  license: LICENSE
  summary: 'Tools for the Brian 2 simulator'
