# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 00:36
from __future__ import unicode_literals

from django.db import migrations, models

from shark.models import MarkdownField


class Migration(migrations.Migration):

    dependencies = [
        ('shark', '0002_auto_20160312_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('url_name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=512, null=True)),
                ('description', models.CharField(max_length=512, null=True)),
                ('body', MarkdownField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
