# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shark', '0003_staticpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='robots_follow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='robots_index',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='sitemap',
            field=models.BooleanField(default=True),
        ),
    ]
