
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4d0c56c99f9196929ee860cd0b60f4adf01b2da3",
 "version": "1.1.122"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
