
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "386f3d52ed05958c5f3a2034d399acb6636e49fa",
 "version": "1.0.0.post.dev183"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
