from setuptools import setup
setup(
  name = 'textpass',
  packages = ['textpass'],
  version = '0.2',
  description = 'Register and authenticate using only a phone number',
  author = 'Cailen McQuattie',
  author_email = 'cailen.mac@gmail.com',
  url = 'https://github.com/pycal/textpass',
  download_url = 'https://github.com/pycal/textpass/tarball/0.2',
  keywords = ['registration', 'authentication', 'mobile'],
  classifiers = [],
  install_requires = [
    'Flask==0.10.1',
    'Flask-SQLAlchemy==2.1',
    'httplib2==0.9.2',
    'itsdangerous==0.24',
    'Jinja2==2.8',
    'MarkupSafe==0.23',
    'PyJWT==1.4.0',
    'pytz==2016.3',
    'six==1.10.0',
    'SQLAlchemy==1.0.12',
    'twilio==5.4.0',
    'Werkzeug==0.11.8',
  ],
)