language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

# Twisted tests currently only work on Python 2.
matrix:
  include:
    - python: "2.7"
      env: TWISTED_REQ="Twisted==13.0.0"
    - python: "2.7"
      env: TWISTED_REQ="Twisted"
    - python: "pypy"
      env: TWISTED_REQ="Twisted==13.0.0"
    - python: "pypy"
      env: TWISTED_REQ="Twisted"

install:
  - pip install -U pip wheel setuptools
  - pip install sphinx $TWISTED_REQ
  - pip install .[test]

script:
  - python -m testtools.run testtools.tests.test_suite
  - make clean-sphinx docs
