package:
  name: pytraj-dev
  version: !!str 0.1.2.dev

requirements:
  build:
    - python
    - cython
    - libcpptraj-dev
    - libnetcdf
  run:
    - python
    - libcpptraj-dev
    - libnetcdf
    - numpy

about:
  home: http://github.com/amber-md/pytraj
  license: BSD
  summary: Python wrapper for cpptraj - a package for data analysis of MD simulations
