# Autogenerated by Astropy's setup.py on 2016-06-21 17:58:07.636769
from __future__ import unicode_literals
import datetime

version = "1.2"
githash = ""


major = 1
minor = 2
bugfix = 0

release = True
timestamp = datetime.datetime(2016, 6, 21, 17, 58, 7, 636769)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
