# {# pkglts, travis
# Config file for automatic testing at travis-ci.org

language: python

python:
{%- for pyver in pysetup.intended_versions %}
  - "{{ pyver[0] }}.{{ pyver[1] }}"
{%- endfor %}

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 - pip install -r requirements.txt
 - pip install -r dvlpt_requirements.txt
{%- if 'coveralls' is available %}
 - pip install coveralls
{% endif %}

# command to run tests, e.g. python setup.py test
script: nosetests

{% if 'coveralls' is available %}
after_success:
  - coveralls
{% endif %}
# #}
