
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "55528250c223e6d1e799857dd1d25b4eec16586e",
 "version": "0.4.post16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
