
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "72d32e823d952052eff14f77085a7e419c7ebd7d",
 "version": "1.0.0.post.dev82"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
