plugins:
  txt_estacion_puan:
    # mandatory properties for every plugin
    module:
      package: metzoo-python-parser-txt-estacion-puan-plugin
      import: from metzoo.plugins import txt_estacion_puan

    # specific properties for the plugin (this could be anything)
    path:         "//aimapuc227/C/Estacion On Line"
    filename:     "downld08.txt"
    lines:        1
  
    mapping:
      "[16:22]":    {agent: "puan.ambiente", metric: "temp.ambiente"}
      "[37:42]":    {agent: "puan.ambiente", metric: "hum.ambiente"}
