sudo: required

language: python

services:
  - redis
  - docker

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

before_install:
  - docker pull mongo:latest
  - docker pull rethinkdb:latest
  - docker run -d -p 127.0.0.1:27017:27017 mongo
  - docker run -d -p 127.0.0.1:28015:28015 rethinkdb

install: pip install tox-travis coveralls

script: tox

after_success: coveralls

notifications:
  irc:
    channels:
      - "chat.freenode.net#apscheduler"
    on_success: change
    use_notice: true
    skip_join: true
