[setup]
statement_files = ["sql/create_countries.sql"]

    [[setup.data_files]]
    target = "countries"
    source = "data/countries.json" # paths are relative to the spec file

[[queries]]
statement = "select count(*) from countries"
iterations = 1000
concurrency = 2

[teardown]
statements = ["drop table countries"]
