

class Enum():

    MAC_ADDRESS_MODE_FIEXD = 'e_mm_fixed'
    MAC_ADDRESS_MODE_INCREMENT = 'e_mm_inc'
    MAC_ADDRESS_MODE_DECREMENT ='e_mm_dec'



    IP4_ADDRESS_MODE_FIEXD = 'e_im_fixed'
    IP4_ADDRESS_MODE_INCREMENT = 'e_im_inc_host'
    IP4_ADDRESS_MODE_DECREMENT ='e_im_dec_host'
    IP4_ADDRESS_MODE_RANDOM ='e_im_random_host'



    ARP_HARDWARE_ADDRESS_MODE_FIEXD = 'kFixed'
    ARP_HARDWARE_ADDRESS_MODE_INCREMENT = 'kIncrement'
    ARP_HARDWARE_ADDRESS_MODE_DECREMENT = 'kDecrement'

    ARP_PROTOCOL_ADDRESS_MODE_FIEXD_HOST = 'kFixedHost'
    ARP_PROTOCOL_ADDRESS_MODE_INCREMENT_HOST = 'kIncrementHost'
    ARP_PROTOCOL_ADDRESS_MODE_DECREMENT_HOST = 'kDecrementHost'
    ARP_PROTOCOL_ADDRESS_MODE_RANDOM_HOST = 'kRandomHost'



    TEXT_PROTOCOL_TEXT_ENCODING_UTF8 = 'kUtf8'

    TEXT_PROTOCOL_END_OF_LINE_CR = 'kCr'
    TEXT_PROTOCOL_END_OF_LINE_LF = 'kLf'
    TEXT_PROTOCOL_END_OF_LINE_CRLF = 'kCrLf'



    PAYLOAD_DATA_PATTERN_MODE_FIXED_WORD = 'e_dp_fixed_word'
    PAYLOAD_DATA_PATTERN_MODE_INCREMENT_BYTE = 'e_dp_inc_byte'
    PAYLOAD_DATA_PATTERN_MODE_DECREMENT_BYTE = 'e_dp_dec_byte'
    PAYLOAD_DATA_PATTERN_MODE_RANDOM = 'e_dp_random'



    IGMP_GROUP_RECORD_TYPE_RESERVED = 'kReserved'
    IGMP_GROUP_RECORD_TYPE_IS_INCLUDE = 'kIsInclude'
    IGMP_GROUP_RECORD_TYPE_IS_EXCLUDE = 'kIsExclude'
    IGMP_GROUP_RECORD_TYPE_TO_INCLUDE = 'kToInclude'
    IGMP_GROUP_RECORD_TYPE_TO_EXCLUDE = 'kToExclude'
    IGMP_GROUP_RECORD_TYPE_ALLOW_NEW = 'kAllowNew'
    IGMP_GROUP_RECORD_TYPE_BLOCK_OLD = 'kBlockOld'

    IGMP_GROUP_MODE_FIXED = 'kFixed'
    IGMP_GROUP_MODE_INCREMENT_GROUP = 'kIncrementGroup'
    IGMP_GROUP_MODE_DECREMENT_GROUP = 'kDecrementGroup'
    IGMP_GROUP_MODE_RANDOM_GROUP = 'kRandomGroup'




    ICMP_VERSION_4 = 'kIcmp4'
    ICMP_VERSION_6 = 'kIcmp6'