language: python
sudo: false
python:
  - "2.7"
  - "3.3"
install:
  - pip install codecov coverage catkin_pkg
script:
  - rm -f .coverage
  - nosetests --with-coverage --cover-package=catkin_lint test
after_success:
  - codecov

