language: c
sudo: required

notifications:
  email:
    recipients:
      - manodeep@gmail.com
    on_success: change
    on_failure: always

env:
  global:
    - NUMPY_VERSION=1.9

addons: 
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - libgsl0-dev

matrix:
  fast_finish: true

  ### let osx fail for the time being, while I figure out the details
  allow_failures:
    os: osx

  include:
    #### osx with clang doesn't use openmp -> so they are the slowest. Run them first
    - os: osx
      compiler: gcc
      env: COMPILER=gcc-4.9 FAMILY=gcc V='4.9' PYTHON_VERSION=2.6 NUMPY_VERSION=1.7 
      before_install:
        # - brew update
        # - brew tap homebrew/versions && brew install gcc48 --without-multilib
        - wget http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -q --yes -n test python=$PYTHON_VERSION numpy=$NUMPY_VERSION
        - source activate test
        - conda install -q --yes -c asmeurer gsl


#    - os: osx
#      compiler: clang
#      env: COMPILER=clang-omp FAMILY=clang V='3.5' PYTHON_VERSION=2.7
#      before_install:
#        - brew update
#        - brew outdated xctool || brew upgrade xctool
#        - brew tap homebrew/versions && brew install clang-omp
#        - wget http://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -O miniconda.sh
#        - bash miniconda.sh -b -p $HOME/miniconda
#        - export PATH="$HOME/miniconda/bin:$PATH"
#        - conda create -q --yes -n test python=$PYTHON_VERSION numpy=$NUMPY_VERSION
#        - source activate test
#        - conda install -q --yes -c asmeurer gsl        

    # - os: osx
    #   compiler: clang
    #   env: COMPILER=clang FAMILY=clang V='Apple LLVM 7.0.0' PYTHON_VERSION=3.5
    #   before_install:
    #     - wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
    #     - bash miniconda.sh -b -p $HOME/miniconda
    #     - export PATH="$HOME/miniconda/bin:$PATH"
    #     - conda create -q --yes -n test python=$PYTHON_VERSION numpy=$NUMPY_VERSION
    #     - source activate test
    #     - conda install -q --yes -c asmeurer gsl

    # - os: osx
    #   compiler: gcc
    #   env: COMPILER=gcc-4.8 V='4.8' PYTHON_VERSION=3.5 FAMILY=gcc
    #   before_install:
    #     - brew update && brew tap homebrew/versions && brew install gcc48 --without-multilib
    #     - wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
    #     - bash miniconda.sh -b -p $HOME/miniconda
    #     - export PATH="$HOME/miniconda/bin:$PATH"
    #     - conda create -q --yes -n test python=$PYTHON_VERSION numpy=$NUMPY_VERSION
    #     - source activate test
    #     - conda install -q --yes -c asmeurer gsl
        
    # - os: linux
    #   dist: trusty
    #   sudo: required
    #   compiler: clang
    #   addons:
    #     apt: 
    #       sources: ['ubuntu-toolchain-r-test','llvm-toolchain-precise-3.6']
    #       packages: ['clang-3.6','libgsl0-dev']
    #   env: COMPILER=clang-3.6 V=3.6 PYTHON_VERSION=2.7 
    #   before_install:
    #     - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    #     - bash miniconda.sh -b -p $HOME/miniconda
    #     - export PATH="$HOME/miniconda/bin:$PATH"
    #     - conda create -q --yes -n test python=$PYTHON_VERSION numpy=$NUMPY_VERSION
    #     - source activate test

    # - os: linux
    #   dist: trusty
    #   sudo: required
    #   compiler: clang
    #   addons:
    #     apt: 
    #       sources: ['ubuntu-toolchain-r-test','llvm-toolchain-precise-3.6']
    #       packages: ['clang-3.6','libgsl0-dev']
    #   env: COMPILER=clang-3.6 V=3.6 PYTHON_VERSION=3.5
    #   before_install:
    #     - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    #     - bash miniconda.sh -b -p $HOME/miniconda
    #     - export PATH="$HOME/miniconda/bin:$PATH"
    #     - conda create -q --yes -n test python=$PYTHON_VERSION numpy=$NUMPY_VERSION
    #     - source activate test
        
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: COMPILER=gcc PYTHON_VERSION=2.6 NUMPY_VERSION=1.7
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -q --yes -n test python=$PYTHON_VERSION numpy=$NUMPY_VERSION
        - source activate test

    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: COMPILER=gcc PYTHON_VERSION=2.7
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -q --yes -n test python=$PYTHON_VERSION numpy=$NUMPY_VERSION
        - source activate test
        
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: COMPILER=gcc PYTHON_VERSION=3.3 
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -q --yes -n test python=$PYTHON_VERSION numpy=$NUMPY_VERSION
        - source activate test

    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: COMPILER=gcc PYTHON_VERSION=3.5
      before_install:
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda create -q --yes -n test python=$PYTHON_VERSION numpy=$NUMPY_VERSION
        - source activate test
        

install:
  - make CC=$COMPILER
  - make install CC=$COMPILER
  - python setup.py install
        
script:
  - make tests CC=$COMPILER
  
