# Autogenerated by Astropy's setup.py on 2016-06-20 00:02:10.355326
from __future__ import unicode_literals
import datetime

version = "1.2"
githash = "b0d4d775e223f769aeac01d9cff227f5fc2489d7"


major = 1
minor = 2
bugfix = 0

release = True
timestamp = datetime.datetime(2016, 6, 20, 0, 2, 10, 355326)
debug = False

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
