language: node_js

sudo: required

node_js:
    - 5.1

addons:
  firefox: "30.0"

env:
  - BROWSER='Chrome'
  - BROWSER='Firefox'
  - BROWSER='Opera'

install:
  - wget http://download1.operacdn.com/pub/opera/desktop/27.0.1689.54/linux/opera-stable_27.0.1689.54_amd64.deb
  - sudo dpkg -i opera-stable_27.0.1689.54_amd64.deb
  - npm install

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - echo "Firefox version => $(firefox -v)"
  - echo "Chromium version => $(chromium-browser --version)"
  - echo "Opera version => $(opera --version)"

script: npm test
