git:
  depth: 1
language: python
python:
  - 3.5
install:
  - pip install tox
script:
  - tox -e lint,py35
sudo: false
# addons:
#   apt:
#     packages:
#     - texlive-latex-base
#     - latex-xcolor
#     - texlive-latex-extra
#     - texlive-luatex
#     - texlive-xetex
#     - pgf
#     - lmodern
#     - lilypond
notifications:
  email: false

deploy:
  # for tests
  - provider: pypi
    distributions: sdist
    server: https://testpypi.python.org/pypi
    user: "Luthaf"
    password:
      secure: "ttS3bXfO1xxtUlUlcy2/UNdoGC7bKQoALKOjvusmg/4VycN8OfID+LBuSorY4L+TLYwBqcUQLvolnLkQHEwsxNPQoKh7dk6DdT0t4n2jM1AXzry6IxEBjeLNRS/eUXsPmv9dSvJMgoUGkn1TnW+DphZzqthFI5zO7DUtooPOCic="
    on:
      branch: travis_deploy

  # for production
  - provider: pypi
    distributions: sdist
    server: https://pypi.python.org/pypi
    user: "Luthaf"
    password:
      secure: NVTS+wQ55gy0w3ENlcJWBz6oKlI6k5+TwNinEl5EjxJXdxYU/rjH6D4Bm47q41hsd3IIPhTzexqCMB+sbuyQR8lIVLVVlFGQlqVw2hY8TZduFTPslnxgsna4zTG9aDwf1dJCI1ouRn6EybbAR0+DikXXTTnbB77n2/r8bJrKd2o=
    on:
      #tags: true
      branch: master
