package:
  name: easyaccess
  version: "1.3.0"

source:
  fn: easyaccess-1.3.0.tar.gz
  md5: f3160dcc95de2a0fe7c29a08c4aa14dd
  url: https://pypi.python.org/packages/22/a9/28586f7623f15ebbfea8c983300b9e3fd7201bf07ca0463a787a2f6329b3/easyaccess-1.3.0.tar.gz
  

build:
  number: 0


requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - future
    - termcolor
    - fitsio >=0.9.8
    - pandas >=0.14
    - oracle-instantclient
    - cx_oracle

test:
  # Python imports
  imports:
    - easyaccess

about:
  home: https://github.com/mgckind/easyaccess
  license: University of Illinois/NCSA Open Source License
  summary: 'Python command line interpreter to access DES Oracle database'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
